### PR TITLE
Make GSL as a Blas/Lapack 3rd party as well as MKL, OpenBLAS, Netlib, Atlas

### LINKED ISSUE #735: MKL and GSL Blas/Lapack 3rd parties incompatibility
When installing MKL the Intel Math Kernel Library and GSL the GNU Scientific Library and using them during ViSP configuration, we get build issues due to incompatibilities between these two Blas/Lapack libraries that define the same functions:
```
In file included from /home/fspindle/visp_ws/3rdparty/mkl/install/mkl/include/mkl.h:31:0,
                 from /home/fspindle/visp_ws/visp/modules/core/src/math/matrix/vpMatrix_lu.cpp:56:
/home/fspindle/visp_ws/3rdparty/mkl/install/mkl/include/mkl_cblas.h:56:34: error: redeclaration of ‘CblasRowMajor’
 enum CBLAS_LAYOUT {CblasRowMajor=101, CblasColMajor=102};
In file included from /usr/include/gsl/gsl_blas_types.h:28:0,
                 from /usr/include/gsl/gsl_blas.h:29,
                 from /usr/include/gsl/gsl_linalg.h:30,
                 from /home/fspindle/visp_ws/visp/modules/core/src/math/matrix/vpMatrix_lu.cpp:50:
/usr/include/gsl/gsl_cblas.h:46:19: note: previous declaration ‘CBLAS_ORDER CblasRowMajor’
 enum CBLAS_ORDER {CblasRowMajor=101, CblasColMajor=102};
```

### PR DESCRIPTION
**Pull request by fspindle**
Changes that were done are resumed hereafter:

- Make GSL usage as a Blas/Lapack 3rd party like MKL, OpenBLAS, Netlib, Atlas (Closes #735)
    - cmake option USE_BLAS/LAPACK allows now to select one 3rd party between
      [ MKL | OpenBLAS | Netlib | Atlas | GSL ]
    - computing SVD when number of rows < number of cols is now possible using GSL
    - extend existing functionalities for all the Lapack 3rd parties
      (a good example is vpMatrix::inverseTriangular() that was not
      implemented for MKL and GSL)
    - make all the vpMatrix functions suffixed with Gsl as deprecated
      (svdGsl(), pseudoInverseGsl()...). For compat with previous releases
      they are keept but excluded from Doxygen documentation
    - in vpConfig.h define VISP_HAVE_LAPACk_MKL in addition of VISP_HAVE_MKL
      to be more explicit. Same for the other Lapack 3rd parties
- Introduce new tutorial for basic linear algebra with Lapack usage
    - shows how to install one of the supported Blas/Lapack 3rd party under Ubuntu
    - compares performances obtained on some choosed basic linear algebra operations
    - save also the benchmarking results obtained with perfMatrixMultiplication to
      have a reference for future optimisation
- Various optimisations using Blas/Lapack or SSE2 in vpMatrix
    - optimise AAt() using Blas/Lapack
    - optimize operator*(const vpForceTwistMatrix &) using SSE2
    - introduce operator*(const vpHomogeneousMatrix &)
    - introduce getLapackMatrixMinSize() and setLapackMatrixMinSize() to
      be able to modify the matrix/vector default min size requested to use
      Lapack for optimization. By defaut, when one of the Lapack 3rd party is available
      Lapack is used

### CODE REVIEW

**Comment by fspindle** [comment]
@s-trinh Could you test on you side please ?

File: 3rdparty/clapack/blas/daxpy.c [hunk 1]
```diff
@@ -0,0 +1,107 @@
+/* daxpy.f -- translated by f2c (version 20061008).
```
Comment (s-trinh) [inline 3rdparty/clapack/blas/daxpy.c:1]: If you have manually converted the Fortran code to C, there is a new [release 3.9.0](https://github.com/Reference-LAPACK/lapack/releases) that can be considered in the future.

If this is already the newest version, I think that the `LAPACK_MAJOR/MINOR/PATCH_VERSION` should be updated.

If it is indeed the 3.2.1 version, this version is a little bit too old (2009). Maybe in the future it could be interesting to see how to do the conversion.

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 2]
```diff
@@ -617,20 +659,38 @@ void vpMatrix::AAt(vpMatrix &B) const
...
-
-      // sum (row i .* row j)
-      double ssum = 0;
-      for (unsigned int k = 0; k < colNum; k++)
-        ssum += *(pi++) * *(pj++);
-
-      B[i][j] = ssum; // upper triangle
-      if (i != j)
-        B[j][i] = ssum; // lower triangle
+  // If available use Lapack only for small matrices
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:662]:
```suggestion
  // If available use Lapack only for large matrices
```

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 3]
```diff
@@ -651,38 +711,44 @@ void vpMatrix::AtA(vpMatrix &B) const
   if ((B.rowNum != colNum) || (B.colNum != colNum))
     B.resize(colNum, colNum, false, false);
 
-#if defined(VISP_HAVE_LAPACK) && !defined(VISP_HAVE_LAPACK_BUILT_IN)
-  double alpha = 1.0;
-  double beta = 0.0;
-  char transa = 'n';
-  char transb = 't';
+  // If available use Lapack only for small matrices
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:714]:
```suggestion
  // If available use Lapack only for large matrices
```

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 4]
```diff
@@ -1030,22 +1096,31 @@ void vpMatrix::multMatrixVector(const vpMatrix &A, const vpColVector &v, vpColVe
   if (A.rowNum != w.rowNum)
     w.resize(A.rowNum, false);
 
-#if defined(VISP_HAVE_LAPACK) && !defined(VISP_HAVE_LAPACK_BUILT_IN)
-  double alpha = 1.0;
-  double beta = 0.0;
-  char trans = 't';
-  int incr = 1;
+  // If available use Lapack only for small matrices
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:1099]:
```suggestion
  // If available use Lapack only for large matrices
```

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 5]
```diff
@@ -1071,30 +1146,37 @@ void vpMatrix::mult2Matrices(const vpMatrix &A, const vpMatrix &B, vpMatrix &C)
                       A.getCols(), B.getRows(), B.getCols()));
   }
 
-#if defined(VISP_HAVE_LAPACK) && !defined(VISP_HAVE_LAPACK_BUILT_IN)
-  double alpha = 1.0;
-  double beta = 0.0;
-  char trans = 'n';
+  // If available use Lapack only for small matrices
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:1149]:
```suggestion
  // If available use Lapack only for large matrices
```

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 6]
```diff
@@ -1119,17 +1201,20 @@ void vpMatrix::mult2Matrices(const vpMatrix &A, const vpMatrix &B, vpRotationMat
                       A.getRows(), A.getCols(), B.getRows(), B.getCols()));
   }
 
+  // Considering perfMatrixMultiplication.cpp benchmark,
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:1204]: Yes using BLAS for `3x3` matrix multiplication is not worthy (too small).

File: modules/detection/test/testAprilTag.cpp [hunk 7]
```diff
@@ -725,9 +725,12 @@ TEST_CASE("Apriltag getTagsPoints3D test", "[apriltag_get_tags_points3D_test]")
     pose.computePose(vpPose::DEMENTHON_VIRTUAL_VS, cMo_manual);
 
     const vpHomogeneousMatrix& cMo = cMo_vec[i];
+    double epsilon = 1e-9;
+    // Note that using epsilon = std::numeric_limits<double>::epsilon() makes this test
+    // failing when none of the Lapack 3rd party libraries, nor the built-in are used
     for (unsigned int row = 0; row < cMo.getRows(); row++) {
       for (unsigned int col = 0; col < cMo.getCols(); col++) {
-        CHECK(vpMath::equal(cMo[row][col], cMo_manual[row][col], std::numeric_limits<double>::epsilon()));
+        CHECK(vpMath::equal(cMo[row][col], cMo_manual[row][col], epsilon));
```
Comment (s-trinh) [inline modules/detection/test/testAprilTag.cpp:733]: Looking at it quicky, this does not seem normal.

We are comparing the cMo estimated using `DEMENTHON_VIRTUAL_VS` inside the `vpDetectorAprilTag` class and manually (getting the 2D/3D points and calling vpPose `DEMENTHON_VIRTUAL_VS` manually).

The result should be strictly identical, it should be equivalent to calling the vpPose function two times with the same input (to be checked if it is really the case?), and yielding a slightly different result.

I will try to investigate.

Comment (s-trinh) [reply modules/detection/test/testAprilTag.cpp:733]: Ok, I did not read the comment above.

I would prefer to keep the `std::numeric_limits<double>::epsilon()` threshold and add an exception for this specific case (but I am not able to reproduce it).

---

BTW, I am testing in a Docker container (Ubuntu 16.04) without any BLAS or LAPACK libraries, and turn the `WITH_LAPACK` variable to false.

<details><summary>ViSP-third-party.txt</summary>
<p>

```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-02T22:01:08Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.5.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 5.4.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Blas/Lapack:                 no
    \- Use MKL:                  no
    \- Use OpenBLAS:             no
    \- Use Atlas:                no
    \- Use Netlib:               no
    \- Use GSL:                  no
    \- Use Lapack (built-in):    no
    Use Eigen3:                  no
    Use OpenCV:                  no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

I am getting this error:

<details><summary>./testAprilTag</summary>
<p>

```

Apriltag family: 36h11
	Pose estimation method: HOMOGRAPHY
		Same size, Tag: 0
			Translation error: 0.00702138 / Rotation error: 0.0228843
		Same size, Tag: 1
			Translation error: 0.000924979 / Rotation error: 0.00172373
		Same size, Tag: 2
			Translation error: 0.0184756 / Rotation error: 0.0213708
		Custom size, Tag: 0
			Translation error: 0.00702138 / Rotation error: 0.0228843
		Custom size, Tag: 1
			Translation error: 0.000924979 / Rotation error: 0.00172373
		Custom size, Tag: 2
			Translation error: 0.0184756 / Rotation error: 0.0213708
		Custom size, Tag: 3
			Translation error: 0.00445275 / Rotation error: 0.0168339
		Custom size, Tag: 4
			Translation error: 0.00727533 / Rotation error: 0.0182167
		Custom size + aligned Z-axis, Tag: 0
			Translation error: 0.00702138 / Rotation error: 0.0185626
		Custom size + aligned Z-axis, Tag: 1
			Translation error: 0.000924979 / Rotation error: 0.00188652
		Custom size + aligned Z-axis, Tag: 2
			Translation error: 0.0184756 / Rotation error: 0.0174533
		Custom size + aligned Z-axis, Tag: 3
			Translation error: 0.00445275 / Rotation error: 0.0217513
		Custom size + aligned Z-axis, Tag: 4
			Translation error: 0.00727533 / Rotation error: 0.0250883
	Pose estimation method: HOMOGRAPHY_VIRTUAL_VS

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testAprilTag is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Apriltag pose estimation test
-------------------------------------------------------------------------------
/workspace/visp/modules/detection/test/testAprilTag.cpp:130
...............................................................................

/workspace/visp/modules/detection/test/testAprilTag.cpp:130: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Cannot compute pseudo-inverse. Install Lapack, Eigen3, OpenCV or GSL 3rd
  party


Apriltag family: 36h11
	id: 0 - RMSE: 0.00028054
	id: 1 - RMSE: 0.000349587
	id: 2 - RMSE: 0.000295341
	id: 3 - RMSE: 0.000150511
	id: 4 - RMSE: 0.000357982

Apriltag family: 25h9
	id: 0 - RMSE: 0.000205857
	id: 1 - RMSE: 0.000282345
	id: 2 - RMSE: 0.00023119
	id: 3 - RMSE: 0.000163054
	id: 4 - RMSE: 0.000308641

Apriltag family: 16h5
	id: 0 - RMSE: 0.000316034
	id: 1 - RMSE: 0.00036884
	id: 2 - RMSE: 0.000330228
	id: 3 - RMSE: 0.00027399
	id: 4 - RMSE: 0.000397781

Apriltag family: CIRCLE21h7
	id: 0 - RMSE: 0.000257834
	id: 1 - RMSE: 0.00027308
	id: 2 - RMSE: 0.000275198
	id: 3 - RMSE: 0.000192135
	id: 4 - RMSE: 0.000201747
-------------------------------------------------------------------------------
Apriltag regression test
-------------------------------------------------------------------------------
/workspace/visp/modules/detection/test/testAprilTag.cpp:434
...............................................................................

/workspace/visp/modules/detection/test/testAprilTag.cpp:434: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Cannot compute pseudo-inverse. Install Lapack, Eigen3, OpenCV or GSL 3rd
  party

-------------------------------------------------------------------------------
Apriltag copy constructor test
-------------------------------------------------------------------------------
/workspace/visp/modules/detection/test/testAprilTag.cpp:533
...............................................................................

/workspace/visp/modules/detection/test/testAprilTag.cpp:533: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Cannot compute pseudo-inverse. Install Lapack, Eigen3, OpenCV or GSL 3rd
  party

-------------------------------------------------------------------------------
Apriltag assignment operator test
-------------------------------------------------------------------------------
/workspace/visp/modules/detection/test/testAprilTag.cpp:599
...............................................................................

/workspace/visp/modules/detection/test/testAprilTag.cpp:599: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Cannot compute pseudo-inverse. Install Lapack, Eigen3, OpenCV or GSL 3rd
  party

-------------------------------------------------------------------------------
Apriltag getTagsPoints3D test
-------------------------------------------------------------------------------
/workspace/visp/modules/detection/test/testAprilTag.cpp:665
...............................................................................

/workspace/visp/modules/detection/test/testAprilTag.cpp:665: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Cannot compute pseudo-inverse. Install Lapack, Eigen3, OpenCV or GSL 3rd
  party

===============================================================================
test cases:   6 |   1 passed | 5 failed
assertions: 137 | 132 passed | 5 failed
```

</p>
</details>

The error makes much sense, and I would prefer just keeping the original threshold `std::numeric_limits<double>::epsilon()`.

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc [hunk 8]
```diff
@@ -0,0 +1,295 @@
...
+that was build setting the appropriate `USE_BLAS/LAPACK=[ MKL | OpenBLAS | Netlib | Atlas | GSL ]` CMake option during configuration.
+
+Moreover, when `OpenBLAS`, `Netlib` or `Atlas` were selected we used `update-alternatives` tool to select the right Lapack library using:
+\verbatim
+$ sudo update-alternatives --config liblapack.so.3-x86_64-linux-gnu
+\endverbatim
+
+Next table summarises the results we obtained:
+
+| Operation Type |   Operation Size  |    MKL    |  OpenBLAS |   Atlas   |   Netlib  |     GSL    |  build-in  | Without Lapack |
```
Comment (s-trinh) [inline doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:271]: For me the timing with Netlib is not correct. It should be more or less similar to built-in.

I will try to run the different benchmark to check this.

File: modules/core/src/math/matrix/vpMatrix.cpp [hunk 9]
```diff
@@ -1246,14 +1364,10 @@ vpMatrix vpMatrix::operator*(const vpVelocityTwistMatrix &V) const
...
 
-#if defined(VISP_HAVE_LAPACK) && !defined(VISP_HAVE_LAPACK_BUILT_IN)
-  double alpha = 1.0;
-  double beta = 0.0;
-  char trans = 'n';
-
-  vpMatrix::blas_dgemm(trans, trans, V.colNum, rowNum, colNum, alpha, V.data, V.colNum, data, colNum, beta, M.data,
-                       V.colNum);
-#else
+  // Considering perfMatrixMultiplication.cpp benchmark,
```
Comment (s-trinh) [inline modules/core/src/math/matrix/vpMatrix.cpp:1367]: I have a small perf degradation. Before with Intel MKL and with: `./testGenericTracker -d -D`

```
Computation time, Mean: 4.7648 ms ; Median: 4.45264 ms ; Std: 2.96486 ms
Max translation error: 0.000958766
Max thetau error: 0.342824

Computation time, Mean: 4.95577 ms ; Median: 4.4342 ms ; Std: 3.97667 ms
Max translation error: 0.000958766
Max thetau error: 0.342824

Computation time, Mean: 5.00756 ms ; Median: 4.47778 ms ; Std: 4.32292 ms
Max translation error: 0.000958766
Max thetau error: 0.342824
```

After:

```
Computation time, Mean: 5.28233 ms ; Median: 4.78821 ms ; Std: 3.886 ms
Max translation error: 0.000956362
Max thetau error: 0.342824

Computation time, Mean: 5.22407 ms ; Median: 4.7417 ms ; Std: 3.83906 ms
Max translation error: 0.000956362
Max thetau error: 0.342824

Computation time, Mean: 5.09045 ms ; Median: 4.7489 ms ; Std: 3.07056 ms
Max translation error: 0.000956362
Max thetau error: 0.342824
```

With `sampling_step==1`:

Before:

```
Computation time, Mean: 29.1824 ms ; Median: 28.1158 ms ; Std: 10.6638 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 29.2613 ms ; Median: 27.8002 ms ; Std: 10.6697 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 29.5986 ms ; Median: 28.3655 ms ; Std: 10.9398 ms
Max translation error: 0.00110701
Max thetau error: 0.372656
```

After:

```
Computation time, Mean: 32.747 ms ; Median: 30.817 ms ; Std: 12.4494 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 32.6962 ms ; Median: 31.8308 ms ; Std: 12.0067 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 32.9085 ms ; Median: 31.1582 ms ; Std: 12.3883 ms
Max translation error: 0.00110701
Max thetau error: 0.372656
```

**Comment by s-trinh** [comment]
## Test with Intel MKL 2019.1.144 and Ubuntu 16.04

`Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz`

### ./testGenericTracker -d -D
- Before:

```
Computation time, Mean: 28.0571 ms ; Median: 26.8651 ms ; Std: 10.0519 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 27.987 ms ; Median: 26.6885 ms ; Std: 10.0708 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 27.9939 ms ; Median: 26.8212 ms ; Std: 10.0406 ms
Max translation error: 0.00110701
Max thetau error: 0.372656
```

- After:

```
Computation time, Mean: 34.196 ms ; Median: 32.1661 ms ; Std: 14.2505 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 33.605 ms ; Median: 31.7834 ms ; Std: 12.7761 ms
Max translation error: 0.00110701
Max thetau error: 0.372656

Computation time, Mean: 33.0729 ms ; Median: 31.5372 ms ; Std: 12.2484 ms
Max translation error: 0.00110701
Max thetau error: 0.372656
```

- Results:
  - small perf degradation

### ./testGenericTracker -d -D (5 back and forth tracking)
The program is modified to run the tracker on the same sequence back and forth 5 times to increase the running time of the program (400 frames instead of 40).

- Before:

```
Computation time, Mean: 27.4078 ms ; Median: 26.2208 ms ; Std: 9.76099 ms
Max translation error: 0.00111751
Max thetau error: 0.372656
Features, Mean: 51405.4 ; Median: 46066 ; Std: 13883.1
```

- After:

```
Computation time, Mean: 30.6809 ms ; Median: 29.6366 ms ; Std: 11.0347 ms
Max translation error: 0.00111751
Max thetau error: 0.372656
Features, Mean: 51404.7 ; Median: 46066 ; Std: 13881.4
```

- Results:
  - small perf degradation is confirmed, see `vpMatrix vpMatrix::operator*(const vpVelocityTwistMatrix &V) const` change
  - not the same mean number of features, can be explained since floating point operations are not computed in the same order between BLAS and SSE2 code
  - [proof](http://cpp.sh/8wm4b): 
```
// Example program
#include <iostream>
#include <string>
#include <iomanip>
#include <limits>

int main()
{
    double val1 = 0.1 + 0.2 + 0.3;
    double val2 = 0.1 + (0.2 + 0.3);
    
    std::cout << "val1: " << std::setprecision(std::numeric_limits<double>::max_digits10) << val1 << std::endl;
    std::cout << "val2: " << std::setprecision(std::numeric_limits<double>::max_digits10) << val2 << std::endl;
}
```
  - see also: [What does gcc's ffast-math actually do?](https://stackoverflow.com/questions/7420665/what-does-gccs-ffast-math-actually-do)

### ./perfMatrixMultiplication --benchmark

- Before:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          152    2.1128 ms 
                                                     136 ns       131 ns       148 ns 
                                                      33 ns         1 ns        66 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100           72    2.1168 ms 
                                                     298 ns       285 ns       331 ns 
                                                      97 ns        29 ns       179 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           63    2.0979 ms 
                                                     333 ns       318 ns       371 ns 
                                                     105 ns         3 ns       202 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           76    2.0976 ms 
                                                     277 ns       276 ns       281 ns 
                                                       8 ns         0 ns        20 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           44    2.1428 ms 
                                                     486 ns       486 ns       489 ns 
                                                       6 ns         0 ns        12 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           62    2.1018 ms 
                                                     339 ns       337 ns       345 ns 
                                                      14 ns         0 ns        34 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           28    2.1252 ms 
                                                     856 ns       854 ns       860 ns 
                                                      12 ns         1 ns        25 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           57    2.1261 ms 
                                                     464 ns       462 ns       472 ns 
                                                      16 ns         1 ns        39 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.1612 ms 
                                                    5.41 us     5.404 us     5.438 us 
                                                      57 ns         7 ns       135 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100           21     2.184 ms 
                                                   1.061 us     1.055 us     1.087 us 
                                                      52 ns         2 ns       125 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1174 ms 
                                                   7.048 us     7.041 us     7.079 us 
                                                      63 ns         5 ns       150 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100           33    2.1516 ms 
                                                     658 ns       653 ns       682 ns 
                                                      48 ns         2 ns       115 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.2522 ms 
                                                 152.326 us   151.987 us   153.071 us 
                                                   2.448 us     1.202 us     4.057 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1     2.399 ms 
                                                  24.237 us    23.894 us    25.394 us 
                                                   2.883 us     1.046 us     6.461 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   470.526 ms 
                                                 4.70783 ms   4.70179 ms   4.71718 ms 
                                                  37.773 us     27.11 us    51.962 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   20.1039 ms 
                                                 201.249 us   200.787 us   203.211 us 
                                                   4.115 us       718 ns     9.611 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   133.006 ms 
                                                 1.33239 ms   1.32951 ms   1.33834 ms 
                                                  20.185 us    12.204 us    36.834 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1    6.1966 ms 
                                                  62.423 us    62.093 us    63.256 us 
                                                     2.5 us     1.154 us     4.647 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    14.8022 s 
                                                 146.127 ms   146.095 ms   146.171 ms 
                                                 190.754 us   146.263 us   268.794 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1   519.368 ms 
                                                 5.19594 ms   5.18278 ms   5.21372 ms 
                                                  77.287 us    61.879 us   100.503 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.96885 s 
                                                  99.665 ms   99.6371 ms   99.6976 ms 
                                                 153.093 us   131.092 us   184.946 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    337.41 ms 
                                                 3.37732 ms   3.36913 ms   3.38891 ms 
                                                      49 us    37.332 us    70.687 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100           73    2.1243 ms 
                                                     289 ns       289 ns       289 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          107    2.1186 ms 
                                                     197 ns       197 ns       198 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100           61    2.1289 ms 
                                                     332 ns       331 ns       334 ns 
                                                       5 ns         0 ns        12 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100           54     2.133 ms 
                                                     395 ns       394 ns       400 ns 
                                                      10 ns         0 ns        22 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          108    2.0952 ms 
                                                     194 ns       194 ns       194 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100           97    2.0952 ms 
                                                     216 ns       216 ns       218 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100           98    2.0972 ms 
                                                     214 ns       214 ns       214 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100           92     2.116 ms 
                                                     229 ns       229 ns       231 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100           93    2.1204 ms 
                                                     228 ns       228 ns       228 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100           90     2.115 ms 
                                                     232 ns       232 ns       234 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100           85    2.1165 ms 
                                                     249 ns       248 ns       249 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100           88     2.112 ms 
                                                     244 ns       240 ns       253 ns 
                                                      25 ns         4 ns        47 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           45     2.133 ms 
                                                     474 ns       473 ns       476 ns 
                                                       6 ns         1 ns        11 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           66    2.1252 ms 
                                                     324 ns       322 ns       329 ns 
                                                      10 ns         0 ns        24 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           22     2.156 ms 
                                                     984 ns       983 ns       988 ns 
                                                       9 ns         3 ns        19 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           71    2.1087 ms 
                                                     306 ns       305 ns       313 ns 
                                                      14 ns         1 ns        33 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           19    2.1603 ms 
                                                    1.14 us     1.138 us      1.15 us 
                                                      20 ns         2 ns        47 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           27    2.1411 ms 
                                                     792 ns       788 ns       812 ns 
                                                      40 ns         2 ns        94 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2     3.262 ms 
                                                  16.604 us    16.457 us    17.301 us 
                                                   1.392 us        67 ns     3.311 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            6    2.1762 ms 
                                                   3.652 us     3.628 us     3.762 us 
                                                     221 ns        10 ns       524 ns 
                                                                                      
(83x201)x(201x1) - Naive code                           100            3    3.1509 ms 
                                                  10.484 us    10.415 us    10.772 us 
                                                     623 ns       109 ns     1.466 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100           10     2.298 ms 
                                                   2.312 us     2.292 us      2.41 us 
                                                     196 ns        10 ns       466 ns 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.0531 ms 
                                                 203.156 us   201.191 us   209.082 us 
                                                  15.019 us     1.856 us    31.968 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1    2.8612 ms 
                                                  29.661 us     28.63 us     32.46 us 
                                                   7.549 us     1.236 us    15.646 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   16.0154 ms 
                                                 161.731 us   159.326 us   168.324 us 
                                                  17.841 us     1.567 us    38.242 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1    2.8045 ms 
                                                   28.98 us    28.123 us    31.444 us 
                                                   6.468 us     1.249 us    13.526 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          109    2.1037 ms 
                                                     192 ns       192 ns       193 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100           76    2.1052 ms 
                                                     283 ns       277 ns       303 ns 
                                                      47 ns         3 ns       105 ns 
                                                                                      
(6x6) - Naive code                                      100           75     2.115 ms 
                                                     342 ns       342 ns       344 ns 
                                                       4 ns         1 ns        10 ns 
                                                                                      
(6x6) - ViSP                                            100           71    2.1158 ms 
                                                     299 ns       298 ns       304 ns 
                                                      10 ns         0 ns        24 ns 
                                                                                      
(8x8) - Naive code                                      100           57    2.1204 ms 
                                                     388 ns       376 ns       414 ns 
                                                      85 ns        42 ns       138 ns 
                                                                                      
(8x8) - ViSP                                            100           66    2.0988 ms 
                                                     318 ns       317 ns       325 ns 
                                                      12 ns         0 ns        30 ns 
                                                                                      
(10x10) - Naive code                                    100           38    2.1128 ms 
                                                     645 ns       643 ns       648 ns 
                                                       8 ns         1 ns        17 ns 
                                                                                      
(10x10) - ViSP                                          100           57    2.1204 ms 
                                                     458 ns       456 ns       466 ns 
                                                      17 ns         1 ns        40 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.1378 ms 
                                                   3.041 us     3.038 us     3.051 us 
                                                      23 ns         4 ns        55 ns 
                                                                                      
(20x20) - ViSP                                          100           26     2.119 ms 
                                                     810 ns       804 ns       839 ns 
                                                      57 ns         1 ns       137 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.2356 ms 
                                                  92.294 us     92.15 us    92.785 us 
                                                   1.214 us       353 ns     2.745 us 
                                                                                      
(6x200) - ViSP                                          100            1    2.4252 ms 
                                                  24.458 us    24.102 us    25.615 us 
                                                   2.971 us     1.074 us     6.672 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.1415 ms 
                                                   4.268 us     4.262 us     4.283 us 
                                                      45 ns        12 ns        82 ns 
                                                                                      
(200x6) - ViSP                                          100           29     2.117 ms 
                                                     734 ns       730 ns       753 ns 
                                                      38 ns         1 ns        90 ns 
                                                                                      
(207x119) - Naive code                                  100            1   141.728 ms 
                                                 1.41905 ms    1.4167 ms   1.42359 ms 
                                                  16.099 us     9.573 us    24.886 us 
                                                                                      
(207x119) - ViSP                                        100            1   12.2029 ms 
                                                 122.145 us   121.856 us   123.387 us 
                                                   2.609 us       427 ns     6.127 us 
                                                                                      
(83x201) - Naive code                                   100            1   146.071 ms 
                                                 1.46293 ms   1.45981 ms   1.46981 ms 
                                                  22.432 us    11.433 us    39.211 us 
                                                                                      
(83x201) - ViSP                                         100            1   13.2674 ms 
                                                 133.486 us   132.473 us    136.72 us 
                                                   7.815 us       447 ns    17.312 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.37365 s 
                                                 53.7401 ms   53.7192 ms   53.7859 ms 
                                                 150.737 us    85.613 us   301.707 us 
                                                                                      
(600x400) - ViSP                                        100            1   331.588 ms 
                                                 3.32119 ms   3.31381 ms   3.33138 ms 
                                                  43.911 us    33.673 us    60.001 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.43208 s 
                                                 74.2995 ms   74.2721 ms   74.3305 ms 
                                                 148.259 us   126.782 us   177.176 us 
                                                                                      
(400x600) - ViSP                                        100            1   507.021 ms 
                                                 5.04478 ms   5.03298 ms    5.0596 ms 
                                                  66.922 us    54.866 us    82.023 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          109    2.1037 ms 
                                                     194 ns       193 ns       197 ns 
                                                       6 ns         0 ns        16 ns 
                                                                                      
(3x3) - ViSP                                            100          109    2.1146 ms 
                                                     192 ns       192 ns       193 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6) - Naive code                                      100           72    2.1096 ms 
                                                     294 ns       294 ns       296 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(6x6) - ViSP                                            100           80     2.104 ms 
                                                     263 ns       262 ns       264 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(8x8) - Naive code                                      100           50       2.1 ms 
                                                     419 ns       418 ns       421 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(8x8) - ViSP                                            100           56    2.1336 ms 
                                                     379 ns       379 ns       381 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(10x10) - Naive code                                    100           34    2.1114 ms 
                                                     712 ns       711 ns       716 ns 
                                                      10 ns         1 ns        23 ns 
                                                                                      
(10x10) - ViSP                                          100           39    2.1411 ms 
                                                     572 ns       571 ns       576 ns 
                                                       9 ns         1 ns        20 ns 
                                                                                      
(20x20) - Naive code                                    100            7     2.156 ms 
                                                   3.067 us     3.064 us     3.081 us 
                                                      28 ns         2 ns        68 ns 
                                                                                      
(20x20) - ViSP                                          100            8    2.2464 ms 
                                                   2.859 us     2.812 us     2.979 us 
                                                     333 ns        28 ns       635 ns 
                                                                                      
(6x200) - Naive code                                    100            6    2.4678 ms 
                                                   4.123 us     4.118 us     4.136 us 
                                                      35 ns         3 ns        64 ns 
                                                                                      
(6x200) - ViSP                                          100            6     2.475 ms 
                                                   4.122 us     4.117 us     4.137 us 
                                                      39 ns         3 ns        72 ns 
                                                                                      
(200x6) - Naive code                                    100            1   10.3012 ms 
                                                  102.16 us   101.649 us   102.406 us 
                                                   1.734 us     1.021 us     2.757 us 
                                                                                      
(200x6) - ViSP                                          100            1    8.7775 ms 
                                                  88.113 us    87.769 us    88.946 us 
                                                   2.552 us       962 ns     4.559 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           49    2.1266 ms 
                                                     446 ns       443 ns       459 ns 
                                                      28 ns         5 ns        65 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           78     2.106 ms 
                                                     270 ns       269 ns       274 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           26    2.1606 ms 
                                                     838 ns       836 ns       844 ns 
                                                      11 ns         0 ns        28 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           58    2.1344 ms 
                                                     374 ns       371 ns       382 ns 
                                                      20 ns         2 ns        37 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.1148 ms 
                                                   5.295 us     5.289 us     5.319 us 
                                                      49 ns         3 ns       117 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           18    2.1762 ms 
                                                   1.268 us     1.258 us     1.314 us 
                                                      91 ns         2 ns       218 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9412 ms 
                                                   14.66 us    14.635 us    14.727 us 
                                                     184 ns        20 ns       385 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            7    2.3205 ms 
                                                   3.341 us     3.315 us     3.455 us 
                                                     231 ns        23 ns       546 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9178 ms 
                                                  29.133 us    29.067 us    29.333 us 
                                                     500 ns        57 ns     1.088 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            4     2.428 ms 
                                                   6.117 us     6.072 us     6.335 us 
                                                     435 ns        15 ns     1.039 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
ViSP/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           49    2.1364 ms 
                                                     445 ns       444 ns       448 ns 
                                                       8 ns         0 ns        17 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           65    2.0995 ms 
                                                     322 ns       322 ns       324 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           26    2.1632 ms 
                                                     833 ns       831 ns       837 ns 
                                                      11 ns         1 ns        23 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           31    2.1576 ms 
                                                     697 ns       696 ns       700 ns 
                                                       7 ns         0 ns        18 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4      2.11 ms 
                                                   5.312 us     5.302 us      5.34 us 
                                                      76 ns         4 ns       147 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            4    2.1496 ms 
                                                    5.42 us     5.412 us     5.451 us 
                                                      67 ns         9 ns       156 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2     2.948 ms 
                                                  14.719 us     14.69 us    14.796 us 
                                                     209 ns        26 ns       408 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2    3.0698 ms 
                                                   15.36 us    15.322 us    15.433 us 
                                                     261 ns       156 ns       397 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9066 ms 
                                                  29.093 us    29.037 us     29.36 us 
                                                     535 ns        26 ns     1.273 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    3.0496 ms 
                                                  30.399 us    30.337 us    30.586 us 
                                                     490 ns       139 ns     1.036 us 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)

```

</p>
</details>

- After:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark
Default matrix/vector min size to enable Blas/Lapack optimization: 0
Used matrix/vector min size to enable Blas/Lapack optimization: 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          155     2.046 ms 
                                                     134 ns       129 ns       147 ns 
                                                      36 ns         1 ns        65 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100           72    2.0736 ms 
                                                     293 ns       281 ns       322 ns 
                                                      82 ns        11 ns       149 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           57     2.052 ms 
                                                     366 ns       352 ns       401 ns 
                                                      97 ns         3 ns       178 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           71     2.059 ms 
                                                     287 ns       280 ns       317 ns 
                                                      60 ns         0 ns       143 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           39     2.067 ms 
                                                     519 ns       508 ns       570 ns 
                                                     103 ns         0 ns       247 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           60      2.07 ms 
                                                     346 ns       339 ns       382 ns 
                                                      69 ns         0 ns       166 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           27    2.0952 ms 
                                                     788 ns       776 ns       846 ns 
                                                     116 ns         0 ns       277 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           54    2.0628 ms 
                                                     404 ns       394 ns       441 ns 
                                                      80 ns         0 ns       186 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4      2.64 ms 
                                                   6.617 us     6.419 us     7.118 us 
                                                   1.397 us        61 ns     2.549 us 
                                                                                      
(20x20)x(20x20) - ViSP                                  100           20     2.128 ms 
                                                   1.067 us      1.04 us     1.167 us 
                                                     221 ns        16 ns       510 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1873 ms 
                                                   7.576 us     7.287 us     8.111 us 
                                                   1.952 us     1.189 us         3 us 
                                                                                      
(6x200)x(200x6) - ViSP                                  100           31    2.0522 ms 
                                                     667 ns       649 ns       727 ns 
                                                     138 ns         8 ns       310 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.7363 ms 
                                                 156.595 us   154.687 us   159.489 us 
                                                  11.844 us     8.439 us     15.24 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1    2.5604 ms 
                                                   26.16 us     25.17 us    28.556 us 
                                                   7.427 us     3.085 us    13.129 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   482.428 ms 
                                                 4.82932 ms    4.8239 ms   4.83556 ms 
                                                  29.589 us    24.618 us    37.047 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   20.9902 ms 
                                                 210.327 us    207.78 us   213.741 us 
                                                  14.946 us    11.907 us    17.761 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   135.064 ms 
                                                 1.34924 ms   1.34525 ms   1.35293 ms 
                                                  19.578 us    16.806 us    22.829 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1    6.4094 ms 
                                                  64.644 us    63.165 us    67.611 us 
                                                  10.195 us     5.892 us    16.478 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    15.3109 s 
                                                 150.707 ms   150.469 ms   150.861 ms 
                                                 965.734 us   678.737 us   1.26953 ms 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1   536.097 ms 
                                                 5.37368 ms   5.36197 ms   5.38756 ms 
                                                   65.03 us    56.393 us     78.19 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.88851 s 
                                                 98.9166 ms   98.8915 ms   98.9456 ms 
                                                 137.817 us   117.386 us    162.87 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1   336.144 ms 
                                                 3.37275 ms   3.36406 ms   3.38774 ms 
                                                   56.64 us    38.727 us   102.528 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100           72    2.0592 ms 
                                                     287 ns       286 ns       288 ns 
                                                       3 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          103    2.0497 ms 
                                                     206 ns       199 ns       225 ns 
                                                      49 ns         2 ns       104 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100           61    2.0557 ms 
                                                     335 ns       334 ns       336 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100           87    2.0532 ms 
                                                     225 ns       224 ns       225 ns 
                                                       2 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          114     2.052 ms 
                                                     180 ns       180 ns       180 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100           97    2.0564 ms 
                                                     212 ns       212 ns       215 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          103    2.0703 ms 
                                                     213 ns       206 ns       228 ns 
                                                      52 ns        32 ns        79 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100           92      2.07 ms 
                                                     225 ns       224 ns       227 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100           94    2.0492 ms 
                                                     217 ns       217 ns       218 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100           90      2.07 ms 
                                                     230 ns       230 ns       232 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100           86    2.0554 ms 
                                                     241 ns       239 ns       253 ns 
                                                      24 ns         1 ns        59 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100           87    2.0532 ms 
                                                     236 ns       235 ns       239 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           45     2.061 ms 
                                                     473 ns       461 ns       499 ns 
                                                      87 ns        41 ns       145 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           67    2.0703 ms 
                                                     304 ns       303 ns       310 ns 
                                                      12 ns         0 ns        29 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           22    2.1428 ms 
                                                     969 ns       967 ns       972 ns 
                                                      10 ns         1 ns        19 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           71    2.0519 ms 
                                                     289 ns       287 ns       295 ns 
                                                      15 ns         0 ns        37 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           19    2.0938 ms 
                                                   1.096 us     1.094 us     1.103 us 
                                                      15 ns         1 ns        37 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           28    2.1252 ms 
                                                     734 ns       730 ns       753 ns 
                                                      38 ns         1 ns        91 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    3.2048 ms 
                                                   16.12 us    15.963 us    16.863 us 
                                                   1.486 us        49 ns     3.536 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            7    2.3632 ms 
                                                   3.398 us     3.378 us     3.479 us 
                                                     198 ns         7 ns       472 ns 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.0886 ms 
                                                  11.196 us    10.791 us    11.972 us 
                                                   2.779 us     1.722 us     4.683 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100           10     2.153 ms 
                                                   2.207 us     2.192 us     2.277 us 
                                                     142 ns         9 ns       340 ns 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.7671 ms 
                                                 210.586 us   207.475 us   218.459 us 
                                                  22.384 us     2.737 us    40.878 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1    2.7495 ms 
                                                  28.501 us    27.536 us    31.052 us 
                                                   7.106 us     1.541 us    14.653 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   17.1398 ms 
                                                 162.495 us   160.205 us   168.907 us 
                                                  17.342 us     4.942 us    36.274 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1    2.6874 ms 
                                                  27.549 us    26.734 us    29.814 us 
                                                   6.149 us     1.186 us    12.955 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          106    2.0564 ms 
                                                     198 ns       195 ns       207 ns 
                                                      23 ns         1 ns        48 ns 
                                                                                      
(3x3) - ViSP                                            100           74    2.0646 ms 
                                                     280 ns       279 ns       285 ns 
                                                      10 ns         0 ns        24 ns 
                                                                                      
(6x6) - Naive code                                      100           74    2.0646 ms 
                                                     281 ns       281 ns       283 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           61    2.0801 ms 
                                                     341 ns       340 ns       347 ns 
                                                      13 ns         1 ns        31 ns 
                                                                                      
(8x8) - Naive code                                      100           52    2.0696 ms 
                                                     408 ns       408 ns       410 ns 
                                                       4 ns         1 ns         9 ns 
                                                                                      
(8x8) - ViSP                                            100           57    2.0634 ms 
                                                     363 ns       361 ns       368 ns 
                                                      11 ns         0 ns        26 ns 
                                                                                      
(10x10) - Naive code                                    100           38    2.0976 ms 
                                                     572 ns       571 ns       576 ns 
                                                       7 ns         0 ns        18 ns 
                                                                                      
(10x10) - ViSP                                          100           55    2.0845 ms 
                                                     402 ns       400 ns       413 ns 
                                                      22 ns         1 ns        52 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.1343 ms 
                                                   3.037 us     3.032 us     3.051 us 
                                                      38 ns         4 ns        69 ns 
                                                                                      
(20x20) - ViSP                                          100           26    2.0826 ms 
                                                     808 ns       800 ns       832 ns 
                                                      61 ns         9 ns       129 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3265 ms 
                                                  94.102 us    93.366 us    96.049 us 
                                                   5.552 us     1.851 us     11.11 us 
                                                                                      
(6x200) - ViSP                                          100            1    2.4109 ms 
                                                  24.424 us    24.075 us    25.687 us 
                                                   3.029 us       815 ns      6.98 us 
                                                                                      
(200x6) - Naive code                                    100            5      2.09 ms 
                                                   4.178 us     4.172 us     4.194 us 
                                                      44 ns         4 ns        81 ns 
                                                                                      
(200x6) - ViSP                                          100           28    2.1028 ms 
                                                     763 ns       756 ns       796 ns 
                                                      66 ns         2 ns       157 ns 
                                                                                      
(207x119) - Naive code                                  100            1   141.517 ms 
                                                 1.41485 ms   1.41309 ms   1.41834 ms 
                                                  12.204 us     7.257 us    18.886 us 
                                                                                      
(207x119) - ViSP                                        100            1   12.1385 ms 
                                                 121.421 us   121.161 us   122.581 us 
                                                   2.379 us       342 ns     5.613 us 
                                                                                      
(83x201) - Naive code                                   100            1   146.861 ms 
                                                 1.46758 ms   1.46662 ms   1.46929 ms 
                                                   6.362 us     4.037 us     9.669 us 
                                                                                      
(83x201) - ViSP                                         100            1   13.2648 ms 
                                                     133 us   132.341 us   134.639 us 
                                                   4.707 us       531 ns     8.679 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.43281 s 
                                                 54.3043 ms   54.2885 ms   54.3237 ms 
                                                  89.241 us    73.257 us   115.635 us 
                                                                                      
(600x400) - ViSP                                        100            1    331.67 ms 
                                                 3.32245 ms   3.31584 ms   3.33092 ms 
                                                  38.116 us    30.765 us    48.696 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.46588 s 
                                                 74.6674 ms   74.6308 ms   74.7346 ms 
                                                 244.745 us   149.688 us   386.409 us 
                                                                                      
(400x600) - ViSP                                        100            1   505.666 ms 
                                                 5.05637 ms   5.04406 ms   5.07129 ms 
                                                   68.91 us    58.305 us    86.739 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          105     2.058 ms 
                                                     197 ns       197 ns       197 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100           70     2.065 ms 
                                                     296 ns       295 ns       300 ns 
                                                       8 ns         0 ns        19 ns 
                                                                                      
(6x6) - Naive code                                      100           74    2.0572 ms 
                                                     280 ns       280 ns       281 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           63    2.0601 ms 
                                                     331 ns       328 ns       340 ns 
                                                      23 ns         0 ns        48 ns 
                                                                                      
(8x8) - Naive code                                      100           50      2.05 ms 
                                                     412 ns       411 ns       414 ns 
                                                       5 ns         2 ns         9 ns 
                                                                                      
(8x8) - ViSP                                            100           59    2.0768 ms 
                                                     369 ns       367 ns       375 ns 
                                                      12 ns         0 ns        30 ns 
                                                                                      
(10x10) - Naive code                                    100           37    2.0572 ms 
                                                     566 ns       565 ns       569 ns 
                                                       7 ns         2 ns        13 ns 
                                                                                      
(10x10) - ViSP                                          100           52    2.0592 ms 
                                                     421 ns       419 ns       431 ns 
                                                      19 ns         1 ns        45 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.2232 ms 
                                                   2.774 us     2.771 us     2.788 us 
                                                      29 ns         3 ns        68 ns 
                                                                                      
(20x20) - ViSP                                          100           24     2.076 ms 
                                                     872 ns       865 ns       901 ns 
                                                      59 ns         2 ns       140 ns 
                                                                                      
(6x200) - Naive code                                    100            5    2.0675 ms 
                                                   4.135 us     4.132 us     4.146 us 
                                                      24 ns         4 ns        58 ns 
                                                                                      
(6x200) - ViSP                                          100           22    2.1472 ms 
                                                     980 ns       973 ns     1.012 us 
                                                      65 ns         2 ns       154 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.7485 ms 
                                                  87.484 us    87.359 us    87.947 us 
                                                   1.063 us       289 ns     2.418 us 
                                                                                      
(200x6) - ViSP                                          100            1    2.4504 ms 
                                                  24.775 us    24.423 us    26.031 us 
                                                   3.064 us       822 ns     7.079 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           48    2.0592 ms 
                                                     429 ns       428 ns       431 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           55    2.0735 ms 
                                                     365 ns       364 ns       367 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           27    2.0601 ms 
                                                     766 ns       764 ns       770 ns 
                                                      11 ns         1 ns        23 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           38    2.0634 ms 
                                                     537 ns       536 ns       542 ns 
                                                      11 ns         1 ns        25 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0992 ms 
                                                   5.246 us     5.239 us     5.275 us 
                                                      59 ns         6 ns       141 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            8    2.3064 ms 
                                                   2.932 us     2.892 us     3.036 us 
                                                     292 ns        76 ns       577 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9474 ms 
                                                  14.747 us    14.717 us    14.825 us 
                                                     215 ns        17 ns       445 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            3    2.4084 ms 
                                                   8.015 us     7.993 us     8.088 us 
                                                     179 ns        35 ns       400 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1     2.906 ms 
                                                  29.097 us    29.027 us    29.329 us 
                                                     555 ns        60 ns     1.238 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    3.1352 ms 
                                                   15.86 us    15.684 us    16.639 us 
                                                   1.598 us       152 ns     3.753 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
ViSP/TMP_BLAS/visp/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           48     2.064 ms 
                                                     429 ns       428 ns       431 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           55     2.079 ms 
                                                     368 ns       366 ns       375 ns 
                                                      16 ns         0 ns        38 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           27    2.0601 ms 
                                                     774 ns       771 ns       780 ns 
                                                      19 ns        10 ns        33 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           38    2.0634 ms 
                                                     538 ns       536 ns       543 ns 
                                                      11 ns         1 ns        26 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0976 ms 
                                                   5.256 us      5.25 us     5.283 us 
                                                      56 ns         5 ns       133 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            8    2.3088 ms 
                                                   2.883 us     2.878 us     2.909 us 
                                                      51 ns         5 ns       122 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9428 ms 
                                                  14.757 us    14.733 us    14.816 us 
                                                     168 ns        17 ns       310 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            3    2.4015 ms 
                                                   8.033 us     8.008 us     8.122 us 
                                                     207 ns        31 ns       474 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1     2.908 ms 
                                                  29.683 us     29.13 us    31.723 us 
                                                   4.615 us       692 ns    10.356 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    3.1388 ms 
                                                  15.723 us    15.683 us    15.872 us 
                                                     340 ns        36 ns       776 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)

```

</p>
</details>

- Results:
  - improvement for `matrix-homogeneous matrix multiplication`
  - improvement for `AAt`
  - perf degradation for `matrix-velocity twist multiplication`
  - improvement for `matrix-force twist multiplication`

**Comment by s-trinh** [comment]
## Test with Docker Ubuntu 18.04 - Atlas

<details><summary>ViSP-third-party.txt (master branch @ 09ff01c)</summary>
<p>

```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T23:01:51Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Use MKL:                     no
    Use OpenBLAS:                no
    Use Atlas:                   yes
    Use Netlib Lapack:           no
    Use Lapack (built-in):       no
    Use Eigen3:                  no
    Use OpenCV:                  no
    Use GSL:                     no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

<details><summary>ViSP-third-party.txt (PR branch)</summary>
<p>


```

==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T20:44:49Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Blas/Lapack:                 yes
    \- Use MKL:                  no
    \- Use OpenBLAS:             no
    \- Use Atlas:                yes
    \- Use Netlib:               no
    \- Use GSL:                  no
    \- Use Lapack (built-in):    no
    Use Eigen3:                  no
    Use OpenCV:                  no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

### ./perfMatrixMultiplication --benchmark

- Before:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          243    2.0412 ms 
                                                      84 ns        84 ns        84 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          123    2.0541 ms 
                                                     165 ns       164 ns       166 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           97    2.0564 ms 
                                                     208 ns       207 ns       209 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           83    2.0667 ms 
                                                     255 ns       242 ns       288 ns 
                                                      92 ns         6 ns       170 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           54    2.0898 ms 
                                                     388 ns       379 ns       411 ns 
                                                      66 ns        30 ns       129 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           63     2.079 ms 
                                                     351 ns       337 ns       373 ns 
                                                      86 ns        60 ns       123 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31    2.0553 ms 
                                                     678 ns       663 ns       747 ns 
                                                     138 ns         9 ns       330 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           42     2.079 ms 
                                                     497 ns       495 ns       504 ns 
                                                      15 ns         1 ns        36 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.1696 ms 
                                                    5.76 us     5.486 us     6.468 us 
                                                    1.95 us        82 ns     3.643 us 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            8    2.1008 ms 
                                                   2.565 us     2.554 us     2.618 us 
                                                     105 ns         2 ns       251 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1681 ms 
                                                   7.144 us     7.137 us     7.175 us 
                                                      64 ns         6 ns       152 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            8    2.0936 ms 
                                                   2.719 us     2.614 us     2.911 us 
                                                     700 ns       437 ns     1.029 us 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.6272 ms 
                                                 153.921 us   152.856 us   156.368 us 
                                                   7.758 us     4.036 us    13.996 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1      7.26 ms 
                                                  73.489 us    72.223 us    76.489 us 
                                                   9.376 us     4.619 us        18 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   481.206 ms 
                                                 4.82744 ms   4.80659 ms   4.85077 ms 
                                                 112.214 us    99.273 us   130.955 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   76.9497 ms 
                                                 762.369 us   757.471 us   771.203 us 
                                                  32.612 us    21.316 us    51.904 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   135.523 ms 
                                                 1.34363 ms   1.33429 ms   1.35593 ms 
                                                  54.271 us     43.95 us     68.03 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   24.9525 ms 
                                                 248.649 us   247.089 us   251.511 us 
                                                  10.448 us     6.405 us    16.052 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    15.1471 s 
                                                 148.501 ms   148.359 ms   148.634 ms 
                                                 700.831 us   630.697 us   781.989 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1    1.95096 s 
                                                 19.4689 ms   19.4391 ms   19.4983 ms 
                                                 151.016 us   136.818 us   168.803 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    10.3542 s 
                                                  102.55 ms   102.446 ms   102.649 ms 
                                                 514.971 us   469.209 us   571.215 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    1.30501 s 
                                                 12.9679 ms   12.9475 ms   12.9865 ms 
                                                  99.066 us    88.629 us   111.624 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          183    2.0496 ms 
                                                     113 ns       112 ns       114 ns 
                                                       3 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          242     2.057 ms 
                                                      84 ns        82 ns        96 ns 
                                                      23 ns         0 ns        51 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          147     2.058 ms 
                                                     140 ns       138 ns       147 ns 
                                                      15 ns         1 ns        36 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          101    2.0604 ms 
                                                     200 ns       199 ns       202 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          288    2.0448 ms 
                                                      71 ns        70 ns        71 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          224    2.0384 ms 
                                                      93 ns        93 ns        94 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          243    2.0412 ms 
                                                      86 ns        86 ns        87 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          199    2.0497 ms 
                                                     101 ns       101 ns       101 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          201    2.0502 ms 
                                                     100 ns       100 ns       101 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          185    2.0535 ms 
                                                     108 ns       108 ns       109 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          162    2.0574 ms 
                                                     124 ns       124 ns       125 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          165     2.046 ms 
                                                     126 ns       125 ns       127 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           67    2.0703 ms 
                                                     308 ns       307 ns       310 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           84     2.058 ms 
                                                     242 ns       241 ns       244 ns 
                                                       5 ns         0 ns        10 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           27    2.0628 ms 
                                                     772 ns       769 ns       777 ns 
                                                      16 ns         5 ns        29 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           31    2.1142 ms 
                                                     666 ns       665 ns       669 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18    2.0862 ms 
                                                   1.161 us     1.159 us      1.17 us 
                                                      19 ns         1 ns        45 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           29    2.1199 ms 
                                                     715 ns       712 ns       726 ns 
                                                      22 ns         1 ns        51 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    3.0382 ms 
                                                  15.379 us    15.234 us    16.083 us 
                                                   1.412 us        42 ns      3.37 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            3    2.2686 ms 
                                                   7.503 us     7.449 us     7.766 us 
                                                     527 ns        11 ns     1.155 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.2634 ms 
                                                  11.784 us    11.482 us    12.352 us 
                                                    2.03 us     1.261 us     3.125 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            5      2.55 ms 
                                                   5.252 us     5.217 us     5.341 us 
                                                     267 ns       133 ns       554 ns 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   21.0267 ms 
                                                 210.535 us   207.005 us   216.222 us 
                                                  22.422 us    16.406 us    33.973 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1    12.689 ms 
                                                 129.229 us   127.314 us   132.275 us 
                                                  12.107 us     8.428 us    16.726 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   16.5844 ms 
                                                 170.032 us   166.827 us   177.182 us 
                                                  23.104 us    12.825 us    41.935 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   12.4245 ms 
                                                 123.243 us   122.038 us   125.521 us 
                                                   8.156 us     4.886 us    12.374 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          265    2.0405 ms 
                                                      75 ns        75 ns        76 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100           86     2.064 ms 
                                                     239 ns       239 ns       241 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(6x6) - Naive code                                      100          132    2.0592 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(6x6) - ViSP                                            100           60     2.076 ms 
                                                     339 ns       338 ns       342 ns 
                                                       8 ns         0 ns        15 ns 
                                                                                      
(8x8) - Naive code                                      100           77    2.0713 ms 
                                                     266 ns       266 ns       268 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           46      2.07 ms 
                                                     435 ns       434 ns       440 ns 
                                                      10 ns         0 ns        24 ns 
                                                                                      
(10x10) - Naive code                                    100           45    2.0745 ms 
                                                     445 ns       445 ns       447 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(10x10) - ViSP                                          100           32    2.1056 ms 
                                                     704 ns       671 ns       776 ns 
                                                     237 ns       137 ns       435 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.1441 ms 
                                                   3.116 us     3.051 us     3.422 us 
                                                     615 ns         4 ns     1.467 us 
                                                                                      
(20x20) - ViSP                                          100            7    2.0685 ms 
                                                   2.971 us     2.963 us     3.002 us 
                                                      73 ns        14 ns       171 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.7061 ms 
                                                  97.297 us    95.321 us   101.038 us 
                                                  13.391 us     8.462 us    22.151 us 
                                                                                      
(6x200) - ViSP                                          100            1    6.3548 ms 
                                                  62.531 us     61.83 us    64.406 us 
                                                   5.167 us       575 ns    10.588 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.1015 ms 
                                                   4.164 us     4.077 us     4.586 us 
                                                     840 ns         3 ns     2.004 us 
                                                                                      
(200x6) - ViSP                                          100            7     2.233 ms 
                                                   3.173 us      3.12 us     3.314 us 
                                                     406 ns       169 ns       814 ns 
                                                                                      
(207x119) - Naive code                                  100            1   145.373 ms 
                                                 1.46317 ms   1.45219 ms   1.47636 ms 
                                                  61.445 us     52.27 us    72.228 us 
                                                                                      
(207x119) - ViSP                                        100            1   35.4038 ms 
                                                 354.374 us    352.04 us    358.13 us 
                                                  14.894 us    10.517 us    22.283 us 
                                                                                      
(83x201) - Naive code                                   100            1    150.51 ms 
                                                  1.5037 ms   1.49503 ms   1.51554 ms 
                                                  51.306 us    40.007 us    67.626 us 
                                                                                      
(83x201) - ViSP                                         100            1   41.2649 ms 
                                                 414.203 us   410.044 us   421.052 us 
                                                  26.643 us    18.647 us    39.375 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.74077 s 
                                                 57.2157 ms   57.1493 ms   57.2748 ms 
                                                 320.399 us    286.07 us    361.52 us 
                                                                                      
(600x400) - ViSP                                        100            1   766.033 ms 
                                                 7.63432 ms   7.60683 ms   7.66057 ms 
                                                 137.354 us   120.761 us   158.376 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.81238 s 
                                                 77.7539 ms   77.6629 ms   77.8391 ms 
                                                 448.836 us   407.054 us    509.11 us 
                                                                                      
(400x600) - ViSP                                        100            1    1.12878 s 
                                                 11.2107 ms   11.1788 ms   11.2389 ms 
                                                 152.839 us   131.495 us   177.594 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          254    2.0574 ms 
                                                      82 ns        80 ns        94 ns 
                                                      23 ns         0 ns        56 ns 
                                                                                      
(3x3) - ViSP                                            100          255      2.04 ms 
                                                      81 ns        80 ns        89 ns 
                                                      16 ns         0 ns        38 ns 
                                                                                      
(6x6) - Naive code                                      100          129    2.0511 ms 
                                                     168 ns       160 ns       184 ns 
                                                      54 ns        33 ns        87 ns 
                                                                                      
(6x6) - ViSP                                            100          130     2.067 ms 
                                                     158 ns       158 ns       159 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(8x8) - Naive code                                      100           74    2.0646 ms 
                                                     282 ns       281 ns       283 ns 
                                                       5 ns         2 ns         9 ns 
                                                                                      
(8x8) - ViSP                                            100           75      2.07 ms 
                                                     278 ns       277 ns       280 ns 
                                                       6 ns         2 ns        14 ns 
                                                                                      
(10x10) - Naive code                                    100           47    2.0868 ms 
                                                     440 ns       439 ns       443 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(10x10) - ViSP                                          100           47     2.068 ms 
                                                     435 ns       435 ns       437 ns 
                                                       6 ns         0 ns        10 ns 
                                                                                      
(20x20) - Naive code                                    100            8     2.232 ms 
                                                   2.793 us     2.788 us     2.807 us 
                                                      38 ns         4 ns        77 ns 
                                                                                      
(20x20) - ViSP                                          100            8    2.1984 ms 
                                                   2.752 us     2.714 us     2.849 us 
                                                     276 ns        53 ns       498 ns 
                                                                                      
(6x200) - Naive code                                    100            6    2.4396 ms 
                                                   4.052 us     4.002 us      4.18 us 
                                                     360 ns        59 ns       661 ns 
                                                                                      
(6x200) - ViSP                                          100            6    2.4552 ms 
                                                   4.107 us     4.093 us     4.158 us 
                                                     109 ns         2 ns       254 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.9214 ms 
                                                  87.261 us    87.008 us      87.9 us 
                                                   1.838 us       402 ns     3.341 us 
                                                                                      
(200x6) - ViSP                                          100            1    8.9473 ms 
                                                  89.467 us    88.265 us    92.017 us 
                                                   8.505 us     4.947 us    15.298 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           85     2.057 ms 
                                                     236 ns       236 ns       239 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           83    2.0501 ms 
                                                     247 ns       247 ns       250 ns 
                                                       5 ns         0 ns        11 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           37    2.1053 ms 
                                                     577 ns       576 ns       580 ns 
                                                       7 ns         0 ns        17 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           45     2.061 ms 
                                                     462 ns       460 ns       467 ns 
                                                      14 ns         2 ns        30 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4     2.088 ms 
                                                   5.113 us     5.101 us     5.142 us 
                                                      81 ns         5 ns       160 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            6    2.2854 ms 
                                                   3.809 us     3.795 us     3.864 us 
                                                     120 ns         5 ns       277 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9584 ms 
                                                  14.431 us    14.412 us    14.511 us 
                                                     168 ns        27 ns       395 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2     2.101 ms 
                                                  10.694 us    10.447 us    11.294 us 
                                                   1.843 us       875 ns     3.584 us 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9243 ms 
                                                  29.604 us    29.503 us    29.874 us 
                                                     742 ns        95 ns     1.548 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    2.0773 ms 
                                                   21.89 us     21.02 us    23.296 us 
                                                   5.555 us     3.777 us     7.762 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           86     2.064 ms 
                                                     236 ns       236 ns       238 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           93    2.0646 ms 
                                                     223 ns       218 ns       236 ns 
                                                      38 ns        17 ns        75 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0772 ms 
                                                     562 ns       562 ns       567 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           37    2.0794 ms 
                                                     551 ns       550 ns       555 ns 
                                                       8 ns         0 ns        19 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0848 ms 
                                                   5.231 us     5.154 us     5.426 us 
                                                     564 ns       118 ns     1.026 us 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            4    2.1516 ms 
                                                   5.434 us     5.427 us     5.463 us 
                                                      68 ns         8 ns       162 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9522 ms 
                                                   15.52 us    14.953 us    16.526 us 
                                                   3.767 us     2.489 us     5.683 us 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2     3.088 ms 
                                                  15.512 us     15.48 us    15.611 us 
                                                     241 ns         9 ns       528 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9397 ms 
                                                   29.88 us    29.291 us    31.092 us 
                                                   4.113 us     2.307 us     6.586 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    3.0736 ms 
                                                  29.967 us    29.905 us    30.253 us 
                                                     585 ns        46 ns     1.393 us 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- After:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark
Default matrix/vector min size to enable Blas/Lapack optimization: 0
Used matrix/vector min size to enable Blas/Lapack optimization: 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          241    2.0485 ms 
                                                      86 ns        86 ns        87 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          128    2.0608 ms 
                                                     162 ns       162 ns       163 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           95    2.0615 ms 
                                                     212 ns       210 ns       218 ns 
                                                      14 ns         0 ns        33 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           84    2.0664 ms 
                                                     236 ns       236 ns       238 ns 
                                                       4 ns         1 ns        11 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           53    2.0617 ms 
                                                     385 ns       377 ns       425 ns 
                                                      79 ns         0 ns       189 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           63    2.0853 ms 
                                                     328 ns       327 ns       333 ns 
                                                      11 ns         1 ns        25 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31    2.0801 ms 
                                                     688 ns       667 ns       786 ns 
                                                     195 ns        11 ns       464 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           42    2.0664 ms 
                                                     529 ns       506 ns       565 ns 
                                                     143 ns       100 ns       205 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.2084 ms 
                                                   5.486 us     5.479 us     5.518 us 
                                                      65 ns         4 ns       155 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            8    2.0992 ms 
                                                   2.581 us     2.534 us     2.777 us 
                                                     412 ns        32 ns       957 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1648 ms 
                                                   7.322 us     7.287 us     7.381 us 
                                                     229 ns       162 ns       368 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            8    2.0656 ms 
                                                   2.577 us     2.568 us     2.617 us 
                                                      81 ns         6 ns       193 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.5249 ms 
                                                 154.119 us   153.286 us   155.693 us 
                                                   5.644 us     3.452 us     8.725 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1    7.2826 ms 
                                                  73.441 us    73.169 us    74.582 us 
                                                   2.455 us       419 ns     5.755 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   491.144 ms 
                                                 4.95514 ms   4.93592 ms   4.97605 ms 
                                                 101.906 us    88.887 us   117.839 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   77.0042 ms 
                                                 759.957 us   756.566 us   765.422 us 
                                                   21.73 us    15.458 us    30.281 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   136.548 ms 
                                                 1.36107 ms   1.35063 ms   1.37627 ms 
                                                  63.577 us    49.018 us    84.258 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   25.1585 ms 
                                                 253.484 us   252.342 us   255.516 us 
                                                   7.571 us     4.855 us    11.125 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    15.0939 s 
                                                 148.291 ms   148.144 ms    148.43 ms 
                                                 728.855 us   657.199 us   816.397 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1     1.9569 s 
                                                 19.4722 ms   19.4399 ms   19.5031 ms 
                                                 161.207 us   143.561 us   181.812 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    10.2383 s 
                                                 101.241 ms    101.14 ms    101.34 ms 
                                                 511.618 us   470.273 us   561.349 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    1.30235 s 
                                                 12.9578 ms   12.9348 ms   12.9778 ms 
                                                 109.211 us    95.292 us   125.687 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          180     2.052 ms 
                                                     115 ns       114 ns       116 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          247    2.0501 ms 
                                                      81 ns        81 ns        81 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          146    2.0586 ms 
                                                     138 ns       137 ns       138 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          181    2.0634 ms 
                                                     115 ns       113 ns       120 ns 
                                                      16 ns         9 ns        24 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          298    2.0562 ms 
                                                      71 ns        70 ns        71 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          224    2.0608 ms 
                                                      92 ns        92 ns        93 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          238    2.0468 ms 
                                                      87 ns        87 ns        88 ns 
                                                       2 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          205      2.05 ms 
                                                     100 ns       100 ns       101 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          197    2.0488 ms 
                                                     102 ns       102 ns       103 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          192    2.0544 ms 
                                                     104 ns       104 ns       105 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          162    2.0574 ms 
                                                     129 ns       128 ns       130 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          169    2.0618 ms 
                                                     122 ns       121 ns       123 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           67    2.0636 ms 
                                                     308 ns       307 ns       309 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           85     2.057 ms 
                                                     245 ns       244 ns       247 ns 
                                                       5 ns         0 ns        11 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           26    2.0618 ms 
                                                     774 ns       773 ns       778 ns 
                                                       8 ns         0 ns        20 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           31    2.1049 ms 
                                                     664 ns       662 ns       670 ns 
                                                      16 ns         0 ns        32 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           19    2.1679 ms 
                                                   1.113 us      1.11 us     1.123 us 
                                                      23 ns         1 ns        51 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           29     2.117 ms 
                                                     715 ns       712 ns       722 ns 
                                                      22 ns         4 ns        41 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    3.1292 ms 
                                                  15.338 us    15.181 us    16.064 us 
                                                   1.466 us        69 ns     3.481 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            3     2.283 ms 
                                                   7.941 us     7.677 us     8.571 us 
                                                   1.956 us       965 ns     3.855 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.2268 ms 
                                                  10.891 us    10.784 us    11.328 us 
                                                     917 ns        50 ns     2.138 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            5      2.55 ms 
                                                   5.294 us      5.14 us     5.645 us 
                                                    1.12 us       628 ns     2.167 us 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   21.3246 ms 
                                                 210.553 us   207.526 us   216.161 us 
                                                  20.369 us    13.284 us    33.701 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1   12.6274 ms 
                                                 128.683 us   126.952 us   131.645 us 
                                                  11.342 us     7.624 us    16.715 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   16.2393 ms 
                                                 165.813 us   162.268 us   172.273 us 
                                                  23.624 us    15.342 us     39.33 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   12.5624 ms 
                                                 128.257 us   126.368 us   131.853 us 
                                                  12.805 us     7.734 us    20.138 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          258     2.064 ms 
                                                      78 ns        78 ns        78 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3) - ViSP                                            100           88     2.068 ms 
                                                     228 ns       227 ns       230 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(6x6) - Naive code                                      100          128    2.0736 ms 
                                                     160 ns       159 ns       161 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100           60     2.082 ms 
                                                     358 ns       345 ns       386 ns 
                                                      93 ns        49 ns       153 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0824 ms 
                                                     273 ns       267 ns       302 ns 
                                                      58 ns         4 ns       138 ns 
                                                                                      
(8x8) - ViSP                                            100           47    2.0727 ms 
                                                     448 ns       439 ns       467 ns 
                                                      65 ns        40 ns       104 ns 
                                                                                      
(10x10) - Naive code                                    100           45    2.0925 ms 
                                                     460 ns       454 ns       477 ns 
                                                      46 ns         5 ns        86 ns 
                                                                                      
(10x10) - ViSP                                          100           33    2.1054 ms 
                                                     632 ns       630 ns       640 ns 
                                                      16 ns         1 ns        37 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.1434 ms 
                                                   3.024 us     2.997 us     3.148 us 
                                                     248 ns        15 ns       585 ns 
                                                                                      
(20x20) - ViSP                                          100            7     2.065 ms 
                                                   2.892 us     2.881 us     2.937 us 
                                                      96 ns         9 ns       223 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.5437 ms 
                                                  94.364 us     93.92 us    95.911 us 
                                                   3.619 us       548 ns     8.096 us 
                                                                                      
(6x200) - ViSP                                          100            1    6.3391 ms 
                                                  66.964 us     64.35 us    72.779 us 
                                                  18.807 us     10.32 us    35.488 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.1035 ms 
                                                   4.267 us      4.17 us     4.474 us 
                                                     688 ns       378 ns      1.16 us 
                                                                                      
(200x6) - ViSP                                          100            7    2.2337 ms 
                                                   3.226 us     3.142 us     3.399 us 
                                                     586 ns       353 ns     1.001 us 
                                                                                      
(207x119) - Naive code                                  100            1   146.382 ms 
                                                 1.45416 ms   1.44464 ms   1.46609 ms 
                                                  54.084 us    45.423 us    64.476 us 
                                                                                      
(207x119) - ViSP                                        100            1   35.2937 ms 
                                                 352.423 us   349.479 us   356.999 us 
                                                  18.519 us    13.205 us    25.603 us 
                                                                                      
(83x201) - Naive code                                   100            1     152.2 ms 
                                                 1.51564 ms   1.51024 ms   1.52201 ms 
                                                   29.79 us    24.875 us    38.946 us 
                                                                                      
(83x201) - ViSP                                         100            1   41.1984 ms 
                                                 414.853 us    414.37 us   416.376 us 
                                                   3.958 us     1.516 us     8.758 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.57751 s 
                                                 55.3394 ms   55.2747 ms   55.4046 ms 
                                                 331.247 us   306.825 us   361.342 us 
                                                                                      
(600x400) - ViSP                                        100            1   756.727 ms 
                                                 7.54574 ms   7.52248 ms   7.56706 ms 
                                                 113.409 us     97.31 us    131.86 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.70679 s 
                                                  76.666 ms   76.5604 ms   76.7708 ms 
                                                 536.034 us   479.862 us   608.073 us 
                                                                                      
(400x600) - ViSP                                        100            1    1.12433 s 
                                                 11.1119 ms   11.0689 ms   11.1522 ms 
                                                 212.701 us   191.667 us   236.404 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          254    2.0574 ms 
                                                      80 ns        78 ns        88 ns 
                                                      17 ns         1 ns        41 ns 
                                                                                      
(3x3) - ViSP                                            100           88    2.0768 ms 
                                                     228 ns       227 ns       231 ns 
                                                       5 ns         0 ns        13 ns 
                                                                                      
(6x6) - Naive code                                      100          128    2.0608 ms 
                                                     157 ns       156 ns       158 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           60      2.07 ms 
                                                     369 ns       352 ns       399 ns 
                                                     111 ns        75 ns       159 ns 
                                                                                      
(8x8) - Naive code                                      100           75      2.07 ms 
                                                     277 ns       277 ns       278 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(8x8) - ViSP                                            100           47    2.0962 ms 
                                                     457 ns       445 ns       512 ns 
                                                     109 ns         1 ns       261 ns 
                                                                                      
(10x10) - Naive code                                    100           45    2.0565 ms 
                                                     469 ns       452 ns       502 ns 
                                                     115 ns        70 ns       204 ns 
                                                                                      
(10x10) - ViSP                                          100           33    2.0889 ms 
                                                     651 ns       633 ns       689 ns 
                                                     126 ns        73 ns       221 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.2496 ms 
                                                   2.743 us     2.735 us     2.762 us 
                                                      55 ns         2 ns       103 ns 
                                                                                      
(20x20) - ViSP                                          100            8    2.3496 ms 
                                                   2.871 us     2.862 us     2.909 us 
                                                      82 ns         6 ns       190 ns 
                                                                                      
(6x200) - Naive code                                    100            5    2.0705 ms 
                                                   4.037 us     4.031 us     4.056 us 
                                                      50 ns         7 ns       105 ns 
                                                                                      
(6x200) - ViSP                                          100            7    2.1364 ms 
                                                    3.18 us     3.066 us     3.405 us 
                                                     780 ns       462 ns     1.188 us 
                                                                                      
(200x6) - Naive code                                    100            1    8.9437 ms 
                                                  88.065 us    87.444 us    90.476 us 
                                                   5.416 us       735 ns    12.488 us 
                                                                                      
(200x6) - ViSP                                          100            1    6.3917 ms 
                                                  64.979 us    63.817 us    67.822 us 
                                                   8.629 us     2.757 us    15.363 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84    2.0664 ms 
                                                     246 ns       245 ns       248 ns 
                                                       6 ns         1 ns        11 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          127    2.0701 ms 
                                                     159 ns       158 ns       161 ns 
                                                       5 ns         2 ns         9 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0952 ms 
                                                     563 ns       561 ns       566 ns 
                                                      10 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           75      2.07 ms 
                                                     265 ns       264 ns       266 ns 
                                                       3 ns         1 ns         7 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.1488 ms 
                                                   5.506 us     5.341 us     5.966 us 
                                                   1.294 us       548 ns     2.727 us 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1857 ms 
                                                   2.009 us     2.004 us     2.036 us 
                                                      54 ns         6 ns       129 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9786 ms 
                                                  15.213 us    15.118 us    15.322 us 
                                                     517 ns       461 ns       578 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1668 ms 
                                                   5.499 us     5.473 us     5.576 us 
                                                     205 ns        46 ns       437 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9618 ms 
                                                  28.954 us    28.867 us    29.176 us 
                                                     632 ns        70 ns     1.176 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.1636 ms 
                                                  10.622 us    10.566 us    10.882 us 
                                                     523 ns        42 ns     1.245 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84     2.058 ms 
                                                     245 ns       239 ns       260 ns 
                                                      42 ns        19 ns        82 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          129     2.064 ms 
                                                     160 ns       159 ns       164 ns 
                                                      10 ns         2 ns        23 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0736 ms 
                                                     576 ns       576 ns       580 ns 
                                                       7 ns         0 ns        18 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           78    2.0826 ms 
                                                     268 ns       267 ns       273 ns 
                                                       8 ns         1 ns        20 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.1448 ms 
                                                   5.376 us     5.359 us     5.404 us 
                                                     108 ns        72 ns       167 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1923 ms 
                                                   1.966 us     1.957 us     1.989 us 
                                                      66 ns        11 ns       126 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9814 ms 
                                                  15.056 us    14.977 us    15.171 us 
                                                     481 ns       364 ns       641 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1816 ms 
                                                   5.356 us     5.336 us     5.433 us 
                                                     170 ns        12 ns       393 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9984 ms 
                                                  28.929 us    28.852 us    29.203 us 
                                                     630 ns        65 ns     1.428 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.1714 ms 
                                                   10.62 us    10.567 us    10.869 us 
                                                     512 ns        37 ns      1.22 us 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- Results:
  - improvement for `matrix-homogeneous matrix multiplication`
  - improvement for `AAt`
  - improvement for `matrix-velocity twist multiplication`
  - improvement for `matrix-force twist multiplication`

### ./testGenericTracker -d -D

- Before:

```
Computation time, Mean: 43.7878 ms ; Median: 41.9232 ms ; Std: 15.5681 ms
Max translation error: 0.00111777
Max thetau error: 0.372656
Features, Mean: 51403.4 ; Median: 46053 ; Std: 13879.4
```

- After:

```
Computation time, Mean: 36.2006 ms ; Median: 34.9214 ms ; Std: 12.6529 ms
Max translation error: 0.00111777
Max thetau error: 0.372656
Features, Mean: 51403.4 ; Median: 46053 ; Std: 13879.4
```

**Comment by s-trinh** [comment]
## Test with Docker Ubuntu 18.04 - OpenBLAS (OpenBLAS 0.2.20)
<details><summary>ViSP-third-party.txt (master branch @ 09ff01c)</summary>
<p>

```

==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T23:02:45Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Use MKL:                     no
    Use OpenBLAS:                yes
    Use Atlas:                   no
    Use Netlib Lapack:           no
    Use Lapack (built-in):       no
    Use Eigen3:                  no
    Use OpenCV:                  no
    Use GSL:                     no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

<details><summary>ViSP-third-party.txt (PR branch)</summary>
<p>


```

==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T20:51:41Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Blas/Lapack:                 yes
    \- Use MKL:                  no
    \- Use OpenBLAS:             yes
    \- Use Atlas:                no
    \- Use Netlib:               no
    \- Use GSL:                  no
    \- Use Lapack (built-in):    no
    Use Eigen3:                  no
    Use OpenCV:                  no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

### ./perfMatrixMultiplication --benchmark

- Before:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          243    1.9926 ms 
                                                      82 ns        82 ns        82 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100           92    2.0148 ms 
                                                     219 ns       219 ns       220 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           97    2.0079 ms 
                                                     208 ns       208 ns       209 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           74    2.0128 ms 
                                                     272 ns       271 ns       276 ns 
                                                       9 ns         0 ns        23 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           54    2.0304 ms 
                                                     379 ns       378 ns       384 ns 
                                                      11 ns         0 ns        25 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           65     2.015 ms 
                                                     310 ns       308 ns       315 ns 
                                                      11 ns         1 ns        26 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           32    2.0608 ms 
                                                     645 ns       644 ns       648 ns 
                                                       7 ns         0 ns        16 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           49    2.0335 ms 
                                                     417 ns       416 ns       424 ns 
                                                      16 ns         1 ns        38 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4     2.118 ms 
                                                   5.315 us     5.306 us     5.337 us 
                                                      63 ns         6 ns       116 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100           18     2.043 ms 
                                                   1.148 us      1.14 us     1.186 us 
                                                      76 ns         2 ns       181 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.0874 ms 
                                                   6.969 us     6.959 us     6.995 us 
                                                      72 ns         5 ns       133 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100           12    2.1384 ms 
                                                   1.824 us     1.785 us     1.965 us 
                                                     311 ns         3 ns       716 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.2242 ms 
                                                 152.281 us   152.146 us   152.599 us 
                                                     986 ns       527 ns     1.928 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1    4.1142 ms 
                                                  41.424 us    41.153 us    42.466 us 
                                                   2.419 us       423 ns     5.661 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   467.098 ms 
                                                  4.6726 ms   4.67148 ms    4.6746 ms 
                                                   7.414 us     4.678 us    10.814 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1    8.6989 ms 
                                                  83.948 us    82.442 us    87.582 us 
                                                  11.207 us     5.301 us    21.005 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1     131.4 ms 
                                                 1.31396 ms   1.31364 ms   1.31461 ms 
                                                   2.243 us     1.373 us     4.068 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1    3.8085 ms 
                                                  37.634 us    36.149 us     41.42 us 
                                                  10.846 us     2.859 us    21.459 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    14.9001 s 
                                                 146.949 ms   146.933 ms   146.974 ms 
                                                  102.04 us    75.344 us   137.286 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1   142.494 ms 
                                                  1.4201 ms   1.40848 ms   1.43587 ms 
                                                  68.283 us    52.584 us      87.8 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    10.1311 s 
                                                 100.225 ms    99.985 ms   100.444 ms 
                                                 1.17183 ms   1.09463 ms   1.21781 ms 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1   94.1485 ms 
                                                 929.568 us   921.726 us   940.459 us 
                                                  46.874 us    37.138 us    63.936 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          181     1.991 ms 
                                                     111 ns       110 ns       112 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          242    1.9844 ms 
                                                      84 ns        83 ns        88 ns 
                                                       9 ns         1 ns        19 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          147    1.9992 ms 
                                                     135 ns       135 ns       136 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100           80     2.008 ms 
                                                     255 ns       252 ns       259 ns 
                                                      15 ns        10 ns        21 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          287    1.9803 ms 
                                                      70 ns        69 ns        70 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          210     1.995 ms 
                                                      95 ns        95 ns        95 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          238    1.9992 ms 
                                                      84 ns        83 ns        86 ns 
                                                       4 ns         1 ns         9 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          174     2.001 ms 
                                                     115 ns       115 ns       116 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          198    1.9998 ms 
                                                     101 ns       101 ns       102 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          178    1.9936 ms 
                                                     113 ns       112 ns       114 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          161    1.9964 ms 
                                                     125 ns       125 ns       126 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          154     2.002 ms 
                                                     131 ns       131 ns       133 ns 
                                                       3 ns         1 ns         8 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           68    2.0264 ms 
                                                     306 ns       305 ns       307 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100          130     2.002 ms 
                                                     155 ns       154 ns       156 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           27    2.0196 ms 
                                                     760 ns       749 ns       788 ns 
                                                      78 ns         7 ns       145 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           81    2.0088 ms 
                                                     250 ns       248 ns       255 ns 
                                                      11 ns         0 ns        26 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18    2.0106 ms 
                                                    1.12 us     1.117 us     1.129 us 
                                                      22 ns         1 ns        48 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           23    2.0608 ms 
                                                     897 ns       894 ns       910 ns 
                                                      26 ns         1 ns        62 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    2.9462 ms 
                                                   14.93 us    14.778 us    15.632 us 
                                                   1.414 us        91 ns     3.352 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            6     2.304 ms 
                                                   3.853 us     3.684 us     4.456 us 
                                                   1.434 us       352 ns     3.244 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.2088 ms 
                                                  11.236 us    10.977 us    12.277 us 
                                                    2.24 us       187 ns     5.197 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            7     2.149 ms 
                                                    3.04 us     2.909 us     3.507 us 
                                                   1.133 us       335 ns     2.594 us 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.5643 ms 
                                                   206.9 us   205.638 us    210.31 us 
                                                   9.257 us       896 ns     18.85 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            3     2.901 ms 
                                                   10.31 us     9.653 us    11.848 us 
                                                   4.831 us     2.417 us     8.668 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   16.2722 ms 
                                                  156.42 us   154.437 us   161.816 us 
                                                  14.562 us     1.596 us    29.818 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            3    2.8557 ms 
                                                   9.925 us     9.383 us    11.354 us 
                                                   4.157 us     1.901 us     8.478 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          264      1.98 ms 
                                                      75 ns        75 ns        76 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100           92    2.0148 ms 
                                                     219 ns       219 ns       221 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6) - Naive code                                      100          130     2.002 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100           74    2.0202 ms 
                                                     276 ns       275 ns       280 ns 
                                                       7 ns         0 ns        17 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0064 ms 
                                                     265 ns       264 ns       266 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(8x8) - ViSP                                            100           64     2.016 ms 
                                                     315 ns       313 ns       320 ns 
                                                      12 ns         1 ns        28 ns 
                                                                                      
(10x10) - Naive code                                    100           45    2.0025 ms 
                                                     447 ns       446 ns       449 ns 
                                                       6 ns         1 ns        13 ns 
                                                                                      
(10x10) - ViSP                                          100           47    2.0022 ms 
                                                     429 ns       427 ns       435 ns 
                                                      16 ns         1 ns        40 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0783 ms 
                                                    2.98 us     2.967 us     3.031 us 
                                                     104 ns         3 ns       243 ns 
                                                                                      
(20x20) - ViSP                                          100           18    2.0772 ms 
                                                    1.16 us     1.151 us     1.194 us 
                                                      83 ns         1 ns       198 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3214 ms 
                                                   93.27 us    93.117 us    93.677 us 
                                                   1.164 us       476 ns     2.371 us 
                                                                                      
(6x200) - ViSP                                          100            1    4.1348 ms 
                                                  41.631 us    41.333 us    42.902 us 
                                                   2.718 us       399 ns     6.413 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.0355 ms 
                                                    4.08 us     4.075 us     4.095 us 
                                                      39 ns         3 ns        83 ns 
                                                                                      
(200x6) - ViSP                                          100           11     2.112 ms 
                                                   1.946 us     1.935 us     1.991 us 
                                                      94 ns         3 ns       222 ns 
                                                                                      
(207x119) - Naive code                                  100            1   141.169 ms 
                                                 1.41222 ms   1.41073 ms   1.41768 ms 
                                                  13.005 us     3.152 us    30.067 us 
                                                                                      
(207x119) - ViSP                                        100            1    5.4536 ms 
                                                  55.001 us    53.672 us    59.059 us 
                                                  10.644 us     4.008 us    23.077 us 
                                                                                      
(83x201) - Naive code                                   100            1   147.002 ms 
                                                 1.46929 ms   1.46888 ms   1.47009 ms 
                                                   2.829 us     1.698 us     5.246 us 
                                                                                      
(83x201) - ViSP                                         100            1    6.2987 ms 
                                                  62.596 us    60.406 us    67.725 us 
                                                  16.154 us     8.186 us    30.457 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.26748 s 
                                                 52.7208 ms   52.7114 ms   52.7352 ms 
                                                  58.597 us    41.839 us    86.522 us 
                                                                                      
(600x400) - ViSP                                        100            1   91.1013 ms 
                                                 907.409 us   902.961 us   916.428 us 
                                                  30.939 us    17.517 us    53.145 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.41135 s 
                                                 74.0816 ms   74.0662 ms   74.1057 ms 
                                                  96.351 us     69.19 us   142.144 us 
                                                                                      
(400x600) - ViSP                                        100            1   135.437 ms 
                                                 1.34791 ms   1.33952 ms      1.36 ms 
                                                   50.97 us    37.555 us    73.703 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          255     1.989 ms 
                                                      78 ns        77 ns        78 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100          257    1.9789 ms 
                                                      76 ns        76 ns        77 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6) - Naive code                                      100          130     2.002 ms 
                                                     153 ns       153 ns       155 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100          130     2.002 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8) - Naive code                                      100           75    2.0175 ms 
                                                     270 ns       269 ns       271 ns 
                                                       4 ns         0 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           75     1.995 ms 
                                                     267 ns       266 ns       268 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(10x10) - Naive code                                    100           47    2.0116 ms 
                                                     430 ns       429 ns       432 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(10x10) - ViSP                                          100           48    2.0352 ms 
                                                     423 ns       422 ns       425 ns 
                                                       6 ns         0 ns        13 ns 
                                                                                      
(20x20) - Naive code                                    100            8     2.172 ms 
                                                   2.725 us     2.722 us      2.74 us 
                                                      29 ns         2 ns        69 ns 
                                                                                      
(20x20) - ViSP                                          100            8    2.1656 ms 
                                                   2.707 us     2.704 us     2.719 us 
                                                      28 ns         2 ns        68 ns 
                                                                                      
(6x200) - Naive code                                    100            6    2.3934 ms 
                                                   3.985 us     3.983 us     3.991 us 
                                                      14 ns         2 ns        33 ns 
                                                                                      
(6x200) - ViSP                                          100            6    2.3916 ms 
                                                   3.992 us      3.99 us     3.999 us 
                                                      18 ns         2 ns        42 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.7448 ms 
                                                  87.438 us    87.389 us    87.546 us 
                                                     352 ns       149 ns       605 ns 
                                                                                      
(200x6) - ViSP                                          100            1    8.7539 ms 
                                                  87.564 us    87.471 us     87.85 us 
                                                     747 ns       278 ns     1.599 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           85     2.006 ms 
                                                     236 ns       236 ns       238 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           74    2.0054 ms 
                                                     272 ns       271 ns       276 ns 
                                                       8 ns         0 ns        20 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0304 ms 
                                                     564 ns       563 ns       569 ns 
                                                       9 ns         1 ns        22 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           49    2.0188 ms 
                                                     414 ns       411 ns       424 ns 
                                                      21 ns         0 ns        49 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0368 ms 
                                                   5.106 us     5.096 us     5.131 us 
                                                      69 ns         4 ns       126 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            8    2.0008 ms 
                                                   2.524 us     2.507 us     2.595 us 
                                                     166 ns        17 ns       394 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.8832 ms 
                                                  14.436 us    14.414 us    14.491 us 
                                                     153 ns         8 ns       282 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            3    2.0439 ms 
                                                   6.834 us     6.785 us     7.023 us 
                                                     448 ns        65 ns     1.058 us 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8669 ms 
                                                   28.72 us    28.666 us    28.857 us 
                                                     382 ns        18 ns       709 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.6452 ms 
                                                  13.345 us    13.263 us    13.653 us 
                                                     721 ns       151 ns     1.675 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           85     2.006 ms 
                                                     236 ns       236 ns       238 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           93    1.9995 ms 
                                                     219 ns       219 ns       220 ns 
                                                       3 ns         1 ns         6 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0304 ms 
                                                     563 ns       561 ns       567 ns 
                                                      10 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           37    2.0239 ms 
                                                     549 ns       547 ns       552 ns 
                                                       8 ns         0 ns        17 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0536 ms 
                                                   5.115 us     5.109 us      5.14 us 
                                                      56 ns         5 ns       134 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            4    2.1124 ms 
                                                   5.291 us     5.284 us     5.318 us 
                                                      62 ns         9 ns       148 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2      2.89 ms 
                                                   14.43 us    14.414 us    14.506 us 
                                                     153 ns         6 ns       365 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2    3.0562 ms 
                                                  15.654 us    15.311 us    16.535 us 
                                                   2.617 us     1.282 us     5.284 us 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.9018 ms 
                                                  28.731 us    28.694 us    28.829 us 
                                                     271 ns        22 ns       531 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    3.0303 ms 
                                                  29.984 us    29.943 us    30.092 us 
                                                     301 ns        23 ns       592 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- After:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark
Default matrix/vector min size to enable Blas/Lapack optimization: 0
Used matrix/vector min size to enable Blas/Lapack optimization: 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          238    1.9992 ms 
                                                      84 ns        84 ns        84 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100           92    2.0056 ms 
                                                     214 ns       213 ns       217 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           96    2.0064 ms 
                                                     209 ns       209 ns       211 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           75    2.0175 ms 
                                                     271 ns       271 ns       275 ns 
                                                       7 ns         1 ns        18 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           53    1.9981 ms 
                                                     379 ns       378 ns       381 ns 
                                                       6 ns         2 ns        13 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           65    1.9955 ms 
                                                     308 ns       307 ns       312 ns 
                                                      10 ns         0 ns        25 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31    2.0181 ms 
                                                     650 ns       649 ns       654 ns 
                                                      11 ns         1 ns        23 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           49    2.0335 ms 
                                                     417 ns       415 ns       426 ns 
                                                      18 ns         0 ns        43 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4     2.134 ms 
                                                   5.344 us     5.334 us     5.372 us 
                                                      75 ns         5 ns       152 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100           18    2.0376 ms 
                                                    1.14 us     1.131 us     1.183 us 
                                                      84 ns         1 ns       201 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3     2.103 ms 
                                                   7.022 us     7.011 us      7.05 us 
                                                      77 ns         4 ns       141 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100           12     2.112 ms 
                                                   1.808 us       1.8 us     1.849 us 
                                                      81 ns         3 ns       194 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.3194 ms 
                                                 153.099 us   152.893 us   153.716 us 
                                                   1.639 us       604 ns     3.535 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1    4.1487 ms 
                                                  41.685 us    41.477 us    42.573 us 
                                                    1.88 us       244 ns     4.423 us 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1     474.9 ms 
                                                 4.75086 ms   4.74692 ms   4.75812 ms 
                                                  26.356 us    16.345 us    48.559 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1    8.5529 ms 
                                                  85.551 us    83.327 us    90.449 us 
                                                  16.108 us     8.091 us    27.482 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   132.342 ms 
                                                 1.32475 ms   1.32348 ms   1.32877 ms 
                                                  10.315 us     3.851 us    22.577 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1    3.7611 ms 
                                                  51.413 us    42.252 us    73.193 us 
                                                  67.547 us    33.198 us   125.569 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    14.7824 s 
                                                 145.952 ms   145.928 ms   145.994 ms 
                                                 155.123 us    101.39 us   285.973 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1   143.575 ms 
                                                 1.41946 ms   1.40799 ms   1.43821 ms 
                                                  72.933 us    50.825 us   124.744 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.90494 s 
                                                 99.0474 ms   99.0309 ms   99.0704 ms 
                                                  97.948 us    75.838 us   129.294 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1   92.7975 ms 
                                                 938.886 us   919.871 us   985.012 us 
                                                 140.549 us    42.103 us    248.79 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          179    1.9869 ms 
                                                     112 ns       111 ns       113 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          248     1.984 ms 
                                                      81 ns        81 ns        82 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          145     2.001 ms 
                                                     137 ns       137 ns       139 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          178    1.9936 ms 
                                                     113 ns       113 ns       114 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          295    1.9765 ms 
                                                      68 ns        68 ns        68 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          208    1.9968 ms 
                                                      96 ns        96 ns        96 ns 
                                                       1 ns         1 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          235    1.9975 ms 
                                                      85 ns        85 ns        86 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          177    2.0001 ms 
                                                     114 ns       113 ns       115 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          196    1.9992 ms 
                                                     102 ns       102 ns       103 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          174     2.001 ms 
                                                     115 ns       115 ns       116 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          160         2 ms 
                                                     125 ns       125 ns       126 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          149    1.9966 ms 
                                                     135 ns       134 ns       136 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           68    2.0196 ms 
                                                     298 ns       297 ns       299 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100          130     2.002 ms 
                                                     155 ns       155 ns       158 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           26     2.002 ms 
                                                     771 ns       770 ns       776 ns 
                                                      10 ns         0 ns        24 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           81    2.0007 ms 
                                                     248 ns       247 ns       253 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18    1.9998 ms 
                                                   1.117 us     1.115 us     1.127 us 
                                                      20 ns         1 ns        45 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           24    2.0832 ms 
                                                     873 ns       868 ns       891 ns 
                                                      37 ns         3 ns        88 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    2.9238 ms 
                                                  14.777 us    14.685 us     15.18 us 
                                                     848 ns        59 ns     2.003 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            6    2.1636 ms 
                                                   3.923 us     3.692 us     4.523 us 
                                                   1.742 us       504 ns     3.408 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.1368 ms 
                                                  10.781 us    10.701 us    11.174 us 
                                                     786 ns        15 ns     1.877 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            7    2.1182 ms 
                                                   3.064 us     2.918 us     3.537 us 
                                                   1.211 us       435 ns     2.719 us 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.8899 ms 
                                                 210.809 us   208.511 us    214.88 us 
                                                   15.26 us    10.068 us    23.345 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            3    2.9643 ms 
                                                  10.121 us     9.629 us    11.393 us 
                                                   3.681 us       918 ns     7.222 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1    16.298 ms 
                                                 156.886 us   154.637 us   162.992 us 
                                                  16.567 us       752 ns    34.993 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            3    2.8005 ms 
                                                   9.839 us     9.259 us    11.638 us 
                                                   4.614 us     1.028 us     9.894 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          260     2.002 ms 
                                                      77 ns        76 ns        77 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100           92    2.0148 ms 
                                                     216 ns       216 ns       218 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(6x6) - Naive code                                      100          127    2.0066 ms 
                                                     156 ns       156 ns       158 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(6x6) - ViSP                                            100           74     1.998 ms 
                                                     271 ns       270 ns       274 ns 
                                                       8 ns         0 ns        19 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0216 ms 
                                                     264 ns       264 ns       266 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(8x8) - ViSP                                            100           65     2.002 ms 
                                                     308 ns       307 ns       314 ns 
                                                      12 ns         0 ns        28 ns 
                                                                                      
(10x10) - Naive code                                    100           45    2.0385 ms 
                                                     455 ns       454 ns       457 ns 
                                                       6 ns         0 ns        13 ns 
                                                                                      
(10x10) - ViSP                                          100           48    2.0352 ms 
                                                     425 ns       423 ns       434 ns 
                                                      17 ns         0 ns        38 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0909 ms 
                                                   3.002 us     2.987 us      3.06 us 
                                                     125 ns         3 ns       290 ns 
                                                                                      
(20x20) - ViSP                                          100           18    2.0664 ms 
                                                   1.153 us     1.144 us     1.188 us 
                                                      85 ns         1 ns       204 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3577 ms 
                                                  93.678 us    93.546 us      94.1 us 
                                                   1.076 us       378 ns     2.354 us 
                                                                                      
(6x200) - ViSP                                          100            1    4.1338 ms 
                                                  41.559 us     41.39 us    42.206 us 
                                                   1.477 us       359 ns     3.406 us 
                                                                                      
(200x6) - Naive code                                    100            5     2.038 ms 
                                                   4.083 us     4.079 us     4.103 us 
                                                      39 ns         4 ns        94 ns 
                                                                                      
(200x6) - ViSP                                          100           11    2.1175 ms 
                                                   1.941 us     1.929 us     1.994 us 
                                                     108 ns         4 ns       255 ns 
                                                                                      
(207x119) - Naive code                                  100            1   141.166 ms 
                                                 1.41537 ms   1.41335 ms   1.41917 ms 
                                                  13.601 us     8.484 us    21.267 us 
                                                                                      
(207x119) - ViSP                                        100            1    5.5061 ms 
                                                  55.019 us    53.463 us    59.089 us 
                                                   11.42 us     1.769 us    22.807 us 
                                                                                      
(83x201) - Naive code                                   100            1   145.356 ms 
                                                  1.4533 ms   1.45243 ms   1.45498 ms 
                                                    5.95 us     3.622 us     9.238 us 
                                                                                      
(83x201) - ViSP                                         100            1      6.22 ms 
                                                  61.308 us    59.842 us    64.727 us 
                                                  10.777 us     4.681 us    18.838 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.48306 s 
                                                 54.8297 ms   54.7867 ms   54.8504 ms 
                                                 145.351 us    78.897 us   280.164 us 
                                                                                      
(600x400) - ViSP                                        100            1   92.6039 ms 
                                                 918.901 us   913.388 us   926.407 us 
                                                  32.475 us    26.254 us    48.659 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.44455 s 
                                                 74.3959 ms   74.3749 ms   74.4229 ms 
                                                 120.224 us    97.784 us   147.347 us 
                                                                                      
(400x600) - ViSP                                        100            1   136.263 ms 
                                                 1.71638 ms    1.6259 ms   1.81614 ms 
                                                 484.062 us    448.05 us   508.649 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          255     1.989 ms 
                                                      79 ns        78 ns        79 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100           93    2.0181 ms 
                                                     217 ns       217 ns       218 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - Naive code                                      100          129    2.0124 ms 
                                                     157 ns       157 ns       158 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           75    2.0025 ms 
                                                     267 ns       266 ns       272 ns 
                                                      10 ns         0 ns        23 ns 
                                                                                      
(8x8) - Naive code                                      100           74     1.998 ms 
                                                     269 ns       268 ns       270 ns 
                                                       4 ns         0 ns         7 ns 
                                                                                      
(8x8) - ViSP                                            100           66    2.0196 ms 
                                                     306 ns       305 ns       313 ns 
                                                      13 ns         0 ns        33 ns 
                                                                                      
(10x10) - Naive code                                    100           46    2.0194 ms 
                                                     440 ns       439 ns       442 ns 
                                                       6 ns         0 ns        12 ns 
                                                                                      
(10x10) - ViSP                                          100           49    2.0335 ms 
                                                     413 ns       412 ns       422 ns 
                                                      17 ns         1 ns        42 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.1888 ms 
                                                   2.742 us     2.737 us     2.755 us 
                                                      35 ns         2 ns        70 ns 
                                                                                      
(20x20) - ViSP                                          100           18    2.0214 ms 
                                                   1.136 us     1.128 us     1.179 us 
                                                      84 ns         1 ns       202 ns 
                                                                                      
(6x200) - Naive code                                    100            5    2.0155 ms 
                                                   4.044 us     4.039 us     4.058 us 
                                                      35 ns         4 ns        76 ns 
                                                                                      
(6x200) - ViSP                                          100           12     2.052 ms 
                                                   1.725 us     1.714 us     1.772 us 
                                                      95 ns         3 ns       224 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.7279 ms 
                                                  87.341 us    87.258 us    87.544 us 
                                                     622 ns       291 ns     1.189 us 
                                                                                      
(200x6) - ViSP                                          100            1    4.1018 ms 
                                                  41.356 us    41.073 us    42.359 us 
                                                   2.382 us       433 ns     5.409 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84     2.016 ms 
                                                     241 ns       240 ns       243 ns 
                                                       6 ns         1 ns        11 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          126    2.0034 ms 
                                                     158 ns       158 ns       160 ns 
                                                       4 ns         1 ns         9 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0268 ms 
                                                     565 ns       564 ns       569 ns 
                                                       9 ns         0 ns        23 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           76    2.0064 ms 
                                                     265 ns       264 ns       270 ns 
                                                       8 ns         0 ns        20 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4     2.104 ms 
                                                   5.277 us     5.242 us     5.363 us 
                                                     260 ns        80 ns       457 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1175 ms 
                                                   1.934 us     1.928 us     1.959 us 
                                                      50 ns         3 ns       121 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9152 ms 
                                                  14.746 us    14.664 us    14.843 us 
                                                     456 ns       396 ns       520 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4     2.128 ms 
                                                   5.342 us     5.324 us     5.398 us 
                                                     146 ns        49 ns       318 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8747 ms 
                                                  28.836 us    28.765 us    29.026 us 
                                                     523 ns        54 ns     1.067 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0974 ms 
                                                  10.593 us    10.517 us    10.789 us 
                                                     568 ns       165 ns     1.039 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84     2.016 ms 
                                                     238 ns       238 ns       240 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          129    1.9995 ms 
                                                     155 ns       155 ns       157 ns 
                                                       3 ns         1 ns         8 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0484 ms 
                                                     564 ns       563 ns       568 ns 
                                                      10 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           77     2.002 ms 
                                                     261 ns       260 ns       265 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0972 ms 
                                                    5.24 us     5.224 us     5.266 us 
                                                     100 ns        67 ns       153 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1142 ms 
                                                   1.938 us     1.932 us     1.962 us 
                                                      54 ns         6 ns       125 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.8974 ms 
                                                  14.591 us    14.521 us     14.69 us 
                                                     421 ns       327 ns       573 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1284 ms 
                                                   5.324 us     5.311 us     5.391 us 
                                                     132 ns         5 ns       316 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8716 ms 
                                                  28.799 us    28.733 us    29.104 us 
                                                     621 ns        51 ns     1.478 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0948 ms 
                                                  10.629 us    10.552 us    10.898 us 
                                                     644 ns       116 ns     1.453 us 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- Results:
  - improvement for `matrix-homogeneous matrix multiplication`
  - improvement for `AAt`
  - improvement for `matrix-velocity twist multiplication`
  - improvement for `matrix-force twist multiplication`

### ./testGenericTracker -d -D

- Before:

```
Computation time, Mean: 40.4066 ms ; Median: 38.4475 ms ; Std: 14.8759 ms
Max translation error: 0.00111751
Max thetau error: 0.372656
Features, Mean: 51404.1 ; Median: 46048.5 ; Std: 13881.2
```

- After:

```
Computation time, Mean: 37.3575 ms ; Median: 35.196 ms ; Std: 13.4441 ms
Max translation error: 0.00111751
Max thetau error: 0.372656
Features, Mean: 51404.1 ; Median: 46048.5 ; Std: 13881.2
```

**Comment by s-trinh** [comment]
## Test with Docker Ubuntu 18.04 - Netlib (3.7.1)

<details><summary>ViSP-third-party.txt (master branch @ 09ff01c)</summary>
<p>

```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T23:04:44Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Use MKL:                     no
    Use OpenBLAS:                no
    Use Atlas:                   no
    Use Netlib Lapack:           yes (ver 3.7.1)
    Use Lapack (built-in):       no
    Use Eigen3:                  no
    Use OpenCV:                  no
    Use GSL:                     no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

<details><summary>ViSP-third-party.txt (PR branch)</summary>
<p>


```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T20:53:42Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Blas/Lapack:                 yes
    \- Use MKL:                  no
    \- Use OpenBLAS:             no
    \- Use Atlas:                no
    \- Use Netlib:               yes (ver 3.7.1)
    \- Use GSL:                  no
    \- Use Lapack (built-in):    no
    Use Eigen3:                  no
    Use OpenCV:                  no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

### ./perfMatrixMultiplication --benchmark

- Before:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          244    2.0252 ms 
                                                      84 ns        82 ns        93 ns 
                                                      17 ns         0 ns        42 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          197    2.0291 ms 
                                                     101 ns       101 ns       101 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           97    2.0273 ms 
                                                     207 ns       207 ns       208 ns 
                                                       0 ns         0 ns         2 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           96    2.0352 ms 
                                                     210 ns       210 ns       211 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           54     2.052 ms 
                                                     388 ns       380 ns       426 ns 
                                                      75 ns         1 ns       179 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           59    2.0355 ms 
                                                     344 ns       343 ns       346 ns 
                                                       5 ns         0 ns        10 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           32    2.0736 ms 
                                                     646 ns       645 ns       649 ns 
                                                       7 ns         0 ns        13 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           36    2.0232 ms 
                                                     569 ns       557 ns       628 ns 
                                                     117 ns         7 ns       279 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4      2.14 ms 
                                                   5.306 us     5.296 us     5.331 us 
                                                      70 ns         4 ns       127 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            6     2.277 ms 
                                                   3.838 us     3.768 us     4.173 us 
                                                     669 ns        39 ns     1.593 us 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1102 ms 
                                                   6.977 us     6.962 us     7.013 us 
                                                     102 ns         5 ns       187 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            6     2.106 ms 
                                                   3.539 us     3.467 us     3.884 us 
                                                     685 ns         3 ns     1.635 us 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.4859 ms 
                                                 154.986 us   153.707 us   157.386 us 
                                                   8.781 us     5.318 us    12.925 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1    12.188 ms 
                                                 121.895 us   121.806 us   122.022 us 
                                                     536 ns       404 ns       745 ns 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   472.301 ms 
                                                 4.72346 ms   4.72242 ms    4.7252 ms 
                                                   6.749 us     4.467 us      9.77 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   213.194 ms 
                                                 2.13267 ms   2.13175 ms   2.13439 ms 
                                                   6.219 us     3.868 us    10.308 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   131.625 ms 
                                                 1.31635 ms    1.3156 ms   1.31816 ms 
                                                   5.553 us     2.364 us    10.268 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   64.9045 ms 
                                                 649.178 us   648.516 us   651.347 us 
                                                   5.469 us     1.963 us    12.212 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    14.7786 s 
                                                 145.849 ms   145.819 ms   145.908 ms 
                                                 208.464 us   117.617 us   350.994 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1    6.10525 s 
                                                 61.0748 ms   61.0538 ms   61.1143 ms 
                                                 142.102 us    84.829 us   244.014 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    10.0633 s 
                                                 100.325 ms   100.308 ms   100.352 ms 
                                                 106.267 us    73.232 us   150.483 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    4.09261 s 
                                                 40.9714 ms   40.9593 ms   40.9962 ms 
                                                  84.447 us    50.179 us   162.718 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          183    2.0313 ms 
                                                     111 ns       110 ns       112 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          245     2.009 ms 
                                                      82 ns        82 ns        83 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          147    2.0286 ms 
                                                     138 ns       137 ns       139 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          132    2.0196 ms 
                                                     153 ns       153 ns       155 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          291    2.0079 ms 
                                                      68 ns        68 ns        69 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          214    2.0116 ms 
                                                      94 ns        94 ns        95 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          240     2.016 ms 
                                                      84 ns        84 ns        85 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          177    2.0178 ms 
                                                     115 ns       115 ns       115 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          200      2.02 ms 
                                                     101 ns       101 ns       102 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          151    2.0234 ms 
                                                     134 ns       134 ns       135 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          163    2.0212 ms 
                                                     125 ns       125 ns       126 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          129    2.0253 ms 
                                                     159 ns       159 ns       159 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           68    2.0468 ms 
                                                     301 ns       301 ns       303 ns 
                                                       4 ns         0 ns         8 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           60     2.028 ms 
                                                     339 ns       339 ns       341 ns 
                                                       4 ns         0 ns         7 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           28    2.0972 ms 
                                                     751 ns       749 ns       755 ns 
                                                      11 ns         0 ns        20 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           18    2.1042 ms 
                                                    1.17 us     1.168 us     1.175 us 
                                                      12 ns         0 ns        23 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           19    2.1242 ms 
                                                   1.123 us     1.121 us     1.131 us 
                                                      17 ns         0 ns        42 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           17    2.1403 ms 
                                                   1.261 us     1.259 us      1.27 us 
                                                      22 ns         7 ns        50 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    3.0072 ms 
                                                  15.072 us    15.024 us    15.241 us 
                                                     401 ns        74 ns       905 ns 
                                                                                      
(207x119)x(119x1) - ViSP                                100            1    2.0409 ms 
                                                  20.449 us    20.377 us    20.687 us 
                                                     567 ns        45 ns     1.262 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.1514 ms 
                                                   10.82 us    10.745 us    11.147 us 
                                                     665 ns        30 ns     1.566 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            2    3.0116 ms 
                                                  15.068 us    15.042 us    15.137 us 
                                                     188 ns        16 ns       391 ns 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1    20.464 ms 
                                                 207.496 us   205.199 us   214.562 us 
                                                  18.403 us     5.876 us    40.106 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1     22.85 ms 
                                                 228.732 us   228.028 us   230.389 us 
                                                   5.225 us     2.187 us     9.172 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   15.9397 ms 
                                                 160.297 us    159.24 us   163.119 us 
                                                    7.72 us       793 ns    15.473 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   23.2319 ms 
                                                 233.863 us   232.948 us   236.685 us 
                                                   7.351 us     2.794 us    16.013 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          268      2.01 ms 
                                                      75 ns        75 ns        76 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100          190     2.014 ms 
                                                     106 ns       106 ns       106 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6) - Naive code                                      100          131    2.0305 ms 
                                                     158 ns       158 ns       160 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100           94    2.0304 ms 
                                                     217 ns       217 ns       218 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(8x8) - Naive code                                      100           77    2.0405 ms 
                                                     266 ns       266 ns       268 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(8x8) - ViSP                                            100           58    2.0532 ms 
                                                     352 ns       352 ns       354 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(10x10) - Naive code                                    100           46    2.0424 ms 
                                                     444 ns       443 ns       446 ns 
                                                       4 ns         1 ns        11 ns 
                                                                                      
(10x10) - ViSP                                          100           36    2.0556 ms 
                                                     567 ns       566 ns       571 ns 
                                                       8 ns         0 ns        20 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0762 ms 
                                                   2.973 us     2.967 us     2.986 us 
                                                      38 ns         2 ns        71 ns 
                                                                                      
(20x20) - ViSP                                          100            6    2.2536 ms 
                                                   3.761 us     3.755 us     3.776 us 
                                                      41 ns         2 ns        76 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3732 ms 
                                                  93.771 us    93.659 us    94.168 us 
                                                     933 ns       249 ns     2.099 us 
                                                                                      
(6x200) - ViSP                                          100            1   12.1744 ms 
                                                  122.29 us   121.806 us   124.519 us 
                                                   4.487 us       519 ns     10.62 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.0365 ms 
                                                   4.076 us     4.071 us      4.09 us 
                                                      39 ns         2 ns        72 ns 
                                                                                      
(200x6) - ViSP                                          100            6     2.127 ms 
                                                   3.546 us     3.543 us     3.564 us 
                                                      36 ns         2 ns        87 ns 
                                                                                      
(207x119) - Naive code                                  100            1   140.989 ms 
                                                 1.40865 ms    1.4082 ms   1.40927 ms 
                                                   2.669 us     2.082 us     3.705 us 
                                                                                      
(207x119) - ViSP                                        100            1    130.87 ms 
                                                 1.30879 ms   1.30803 ms   1.30955 ms 
                                                   3.874 us     3.461 us      4.38 us 
                                                                                      
(83x201) - Naive code                                   100            1   146.202 ms 
                                                 1.46327 ms   1.46182 ms   1.46693 ms 
                                                  10.909 us     3.686 us    21.592 us 
                                                                                      
(83x201) - ViSP                                         100            1   141.343 ms 
                                                 1.41408 ms   1.41358 ms   1.41485 ms 
                                                    3.12 us     2.236 us     4.979 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.42611 s 
                                                 54.2525 ms   54.2463 ms   54.2602 ms 
                                                  34.956 us    28.593 us    49.156 us 
                                                                                      
(600x400) - ViSP                                        100            1    4.47239 s 
                                                 44.8177 ms    44.791 ms    44.848 ms 
                                                 144.827 us   127.606 us   179.715 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.51135 s 
                                                 75.0215 ms   75.0109 ms   75.0345 ms 
                                                  59.686 us    50.056 us    73.994 us 
                                                                                      
(400x600) - ViSP                                        100            1    6.58773 s 
                                                 65.9074 ms   65.8879 ms     65.94 ms 
                                                 125.803 us    84.656 us    229.97 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          259    2.0202 ms 
                                                      78 ns        77 ns        78 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100          259    2.0202 ms 
                                                      76 ns        76 ns        77 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6) - Naive code                                      100          131    2.0305 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100          132    2.0328 ms 
                                                     153 ns       153 ns       154 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0444 ms 
                                                     268 ns       267 ns       269 ns 
                                                       4 ns         0 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           76    2.0368 ms 
                                                     271 ns       271 ns       272 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(10x10) - Naive code                                    100           48    2.0448 ms 
                                                     427 ns       426 ns       429 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(10x10) - ViSP                                          100           48    2.0304 ms 
                                                     423 ns       422 ns       426 ns 
                                                       7 ns         0 ns        13 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.1696 ms 
                                                    2.72 us     2.714 us     2.734 us 
                                                      39 ns         4 ns        77 ns 
                                                                                      
(20x20) - ViSP                                          100            8      2.16 ms 
                                                   2.705 us       2.7 us     2.723 us 
                                                      43 ns         2 ns        92 ns 
                                                                                      
(6x200) - Naive code                                    100            6    2.3928 ms 
                                                   3.985 us     3.983 us     3.995 us 
                                                      20 ns         2 ns        47 ns 
                                                                                      
(6x200) - ViSP                                          100            6    2.3928 ms 
                                                   3.989 us     3.985 us     4.001 us 
                                                      31 ns         2 ns        63 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.7513 ms 
                                                  87.567 us    87.512 us    87.689 us 
                                                     407 ns       239 ns       647 ns 
                                                                                      
(200x6) - ViSP                                          100            1    8.7569 ms 
                                                  87.642 us    87.537 us    87.925 us 
                                                     817 ns       348 ns     1.705 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           86    2.0296 ms 
                                                     237 ns       236 ns       238 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           96    2.0352 ms 
                                                     215 ns       215 ns       217 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0232 ms 
                                                     563 ns       562 ns       567 ns 
                                                      10 ns         0 ns        21 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           42    2.0496 ms 
                                                     491 ns       490 ns       493 ns 
                                                       6 ns         2 ns        15 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4     2.042 ms 
                                                    5.11 us     5.103 us     5.143 us 
                                                      66 ns         4 ns       158 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            5    2.2125 ms 
                                                   4.439 us      4.43 us     4.461 us 
                                                      65 ns        13 ns       126 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.8846 ms 
                                                  14.436 us     14.41 us    14.504 us 
                                                     186 ns         7 ns       347 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2    2.5308 ms 
                                                  12.734 us    12.653 us    13.082 us 
                                                     735 ns        99 ns     1.731 us 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8739 ms 
                                                  28.768 us    28.749 us    28.853 us 
                                                     173 ns        15 ns       412 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    2.4946 ms 
                                                  24.969 us    24.926 us    25.081 us 
                                                     325 ns       151 ns       689 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           86    2.0382 ms 
                                                     238 ns       238 ns       240 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           94    2.0304 ms 
                                                     216 ns       216 ns       217 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0232 ms 
                                                     563 ns       562 ns       567 ns 
                                                       9 ns         0 ns        20 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           37    2.0239 ms 
                                                     549 ns       548 ns       552 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4     2.042 ms 
                                                   5.114 us     5.106 us     5.135 us 
                                                      59 ns        13 ns       110 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            4    2.1176 ms 
                                                   5.294 us     5.289 us     5.314 us 
                                                      45 ns         9 ns       107 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.8818 ms 
                                                   14.44 us    14.418 us    14.497 us 
                                                     159 ns         9 ns       297 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2     3.022 ms 
                                                  15.742 us    15.144 us    17.265 us 
                                                    4.24 us       276 ns     7.848 us 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8752 ms 
                                                  28.816 us    28.748 us    29.024 us 
                                                     512 ns        28 ns      1.12 us 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    2.9899 ms 
                                                  29.896 us    29.853 us    30.007 us 
                                                     312 ns        24 ns       585 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- After:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark
Default matrix/vector min size to enable Blas/Lapack optimization: 0
Used matrix/vector min size to enable Blas/Lapack optimization: 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          238    1.9992 ms 
                                                      85 ns        85 ns        85 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          202    1.9998 ms 
                                                      99 ns        99 ns       100 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           96    2.0064 ms 
                                                     209 ns       209 ns       211 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           97    2.0079 ms 
                                                     208 ns       208 ns       210 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           54    2.0358 ms 
                                                     377 ns       376 ns       379 ns 
                                                       4 ns         0 ns         8 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           59    2.0237 ms 
                                                     344 ns       343 ns       346 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31    2.0057 ms 
                                                     647 ns       646 ns       650 ns 
                                                       9 ns         0 ns        18 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           36     2.016 ms 
                                                     562 ns       561 ns       565 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.1348 ms 
                                                    5.34 us      5.33 us     5.364 us 
                                                      68 ns         4 ns       127 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            6    2.2398 ms 
                                                   3.739 us     3.732 us     3.758 us 
                                                      52 ns         3 ns        97 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1039 ms 
                                                   7.031 us      7.02 us     7.057 us 
                                                      74 ns         4 ns       136 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            6    2.0934 ms 
                                                   3.484 us     3.479 us     3.497 us 
                                                      37 ns         6 ns        68 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.2815 ms 
                                                 153.427 us   152.941 us   154.281 us 
                                                   3.196 us     2.075 us      4.54 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1   12.1248 ms 
                                                 121.252 us   121.179 us   121.366 us 
                                                     458 ns       319 ns       667 ns 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   484.499 ms 
                                                 4.84659 ms   4.84374 ms   4.84978 ms 
                                                  15.395 us    11.682 us    20.459 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   216.419 ms 
                                                 2.16593 ms   2.16391 ms   2.17353 ms 
                                                    17.5 us     4.358 us    40.128 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   132.244 ms 
                                                 1.32468 ms   1.32287 ms   1.32947 ms 
                                                  13.917 us     6.154 us    28.463 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   64.9443 ms 
                                                 650.044 us   649.276 us   651.909 us 
                                                   5.697 us     2.137 us    10.777 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1    14.6567 s 
                                                 144.705 ms    144.69 ms   144.727 ms 
                                                  92.196 us    70.505 us   124.586 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1    6.06177 s 
                                                 60.6361 ms     60.62 ms   60.6548 ms 
                                                   88.23 us    75.346 us   112.378 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.94111 s 
                                                 99.4159 ms   99.4023 ms   99.4358 ms 
                                                  83.093 us    63.368 us   120.594 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    4.08291 s 
                                                 40.6816 ms   40.6706 ms   40.6998 ms 
                                                   70.67 us     50.05 us   115.824 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          180     1.998 ms 
                                                     113 ns       112 ns       114 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          246    1.9926 ms 
                                                      82 ns        82 ns        82 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          144    2.0016 ms 
                                                     140 ns       140 ns       142 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          179    2.0048 ms 
                                                     112 ns       112 ns       113 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          292    1.9856 ms 
                                                      68 ns        68 ns        68 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          215    1.9995 ms 
                                                      93 ns        93 ns        93 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          235    1.9975 ms 
                                                      85 ns        84 ns        85 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          178    1.9936 ms 
                                                     112 ns       112 ns       112 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          196    1.9992 ms 
                                                     102 ns       102 ns       103 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          153    2.0043 ms 
                                                     132 ns       132 ns       132 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          160         2 ms 
                                                     125 ns       125 ns       126 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          130     2.002 ms 
                                                     155 ns       154 ns       155 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           67    2.0167 ms 
                                                     300 ns       300 ns       302 ns 
                                                       4 ns         0 ns         7 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           60     2.022 ms 
                                                     339 ns       338 ns       341 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           26    2.0046 ms 
                                                     772 ns       771 ns       775 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           18    2.0988 ms 
                                                   1.168 us     1.167 us     1.172 us 
                                                       8 ns         1 ns        19 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18    2.0034 ms 
                                                   1.113 us      1.11 us     1.123 us 
                                                      23 ns         1 ns        51 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           17     2.125 ms 
                                                   1.278 us     1.261 us      1.32 us 
                                                     122 ns        24 ns       222 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    2.9846 ms 
                                                  15.023 us    14.911 us     15.53 us 
                                                    1.03 us        52 ns     2.439 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            1    2.0444 ms 
                                                  20.498 us     20.46 us    20.593 us 
                                                     272 ns        39 ns       494 ns 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.1536 ms 
                                                  10.822 us    10.752 us    11.097 us 
                                                     595 ns        30 ns     1.386 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            2    3.0116 ms 
                                                  15.102 us    15.077 us    15.166 us 
                                                     180 ns        13 ns       355 ns 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.4372 ms 
                                                 206.427 us   204.374 us   212.403 us 
                                                  15.646 us     1.699 us    33.688 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1   22.8068 ms 
                                                 228.235 us    227.77 us   229.448 us 
                                                   3.436 us       816 ns     6.739 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1    16.467 ms 
                                                 165.482 us   164.638 us   167.737 us 
                                                   6.332 us     1.108 us    12.647 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   23.2313 ms 
                                                 232.716 us   232.323 us   233.719 us 
                                                   2.908 us       634 ns     5.536 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          261    2.0097 ms 
                                                      77 ns        77 ns        77 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100          194    1.9982 ms 
                                                     103 ns       102 ns       103 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(6x6) - Naive code                                      100          129    2.0124 ms 
                                                     155 ns       155 ns       157 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           94     2.021 ms 
                                                     215 ns       214 ns       216 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(8x8) - Naive code                                      100           75    2.0175 ms 
                                                     269 ns       269 ns       271 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           57    2.0235 ms 
                                                     359 ns       359 ns       361 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(10x10) - Naive code                                    100           45     2.043 ms 
                                                     452 ns       452 ns       454 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(10x10) - ViSP                                          100           36    2.0304 ms 
                                                     565 ns       564 ns       568 ns 
                                                       7 ns         0 ns        15 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0944 ms 
                                                    2.99 us     2.986 us     3.004 us 
                                                      34 ns         2 ns        81 ns 
                                                                                      
(20x20) - ViSP                                          100            6    2.2512 ms 
                                                   3.758 us      3.75 us     3.783 us 
                                                      61 ns         3 ns       134 ns 
                                                                                      
(6x200) - Naive code                                    100            1     9.346 ms 
                                                  93.615 us    93.398 us     94.17 us 
                                                   1.561 us       233 ns     2.854 us 
                                                                                      
(6x200) - ViSP                                          100            1   12.1572 ms 
                                                 121.615 us   121.473 us   121.787 us 
                                                     793 ns       665 ns     1.042 us 
                                                                                      
(200x6) - Naive code                                    100            5     2.039 ms 
                                                    4.08 us     4.074 us     4.098 us 
                                                      45 ns         4 ns        98 ns 
                                                                                      
(200x6) - ViSP                                          100            6    2.1246 ms 
                                                   3.549 us     3.546 us     3.567 us 
                                                      35 ns         2 ns        83 ns 
                                                                                      
(207x119) - Naive code                                  100            1   140.885 ms 
                                                 1.40953 ms   1.40903 ms   1.41105 ms 
                                                   4.093 us     1.661 us     8.933 us 
                                                                                      
(207x119) - ViSP                                        100            1   131.916 ms 
                                                 1.31662 ms   1.31601 ms   1.31726 ms 
                                                   3.181 us     2.762 us     3.766 us 
                                                                                      
(83x201) - Naive code                                   100            1   146.867 ms 
                                                 1.46885 ms   1.46845 ms   1.46961 ms 
                                                   2.708 us     1.655 us     4.822 us 
                                                                                      
(83x201) - ViSP                                         100            1   143.619 ms 
                                                 1.43261 ms   1.43177 ms    1.4336 ms 
                                                   4.626 us     3.871 us     5.903 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.38762 s 
                                                 53.8913 ms   53.8852 ms   53.8994 ms 
                                                  35.609 us    28.171 us    48.554 us 
                                                                                      
(600x400) - ViSP                                        100            1    4.40116 s 
                                                 44.0792 ms   44.0574 ms   44.1074 ms 
                                                 125.281 us   105.645 us   169.348 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.38079 s 
                                                 73.7922 ms   73.7811 ms   73.8126 ms 
                                                   74.37 us    47.832 us   124.489 us 
                                                                                      
(400x600) - ViSP                                        100            1    6.48048 s 
                                                 64.9264 ms    64.905 ms   64.9535 ms 
                                                 122.143 us    99.017 us   168.401 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          250         2 ms 
                                                      83 ns        82 ns        83 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100          191    2.0055 ms 
                                                     104 ns       104 ns       105 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(6x6) - Naive code                                      100          129    2.0124 ms 
                                                     156 ns       156 ns       157 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6) - ViSP                                            100           89    2.0114 ms 
                                                     220 ns       216 ns       231 ns 
                                                      30 ns         6 ns        64 ns 
                                                                                      
(8x8) - Naive code                                      100           74    2.0202 ms 
                                                     272 ns       271 ns       273 ns 
                                                       3 ns         0 ns         6 ns 
                                                                                      
(8x8) - ViSP                                            100           57    2.0349 ms 
                                                     356 ns       355 ns       358 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(10x10) - Naive code                                    100           46    2.0286 ms 
                                                     439 ns       438 ns       441 ns 
                                                       5 ns         1 ns        11 ns 
                                                                                      
(10x10) - ViSP                                          100           31    2.0615 ms 
                                                     669 ns       668 ns       672 ns 
                                                       7 ns         1 ns        16 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.1952 ms 
                                                   2.746 us     2.742 us     2.757 us 
                                                      30 ns         2 ns        56 ns 
                                                                                      
(20x20) - ViSP                                          100            5     2.228 ms 
                                                   4.458 us     4.454 us     4.475 us 
                                                      38 ns         4 ns        91 ns 
                                                                                      
(6x200) - Naive code                                    100            5     2.012 ms 
                                                    4.03 us     4.026 us     4.043 us 
                                                      30 ns         5 ns        71 ns 
                                                                                      
(6x200) - ViSP                                          100            4    2.6364 ms 
                                                   6.596 us      6.59 us     6.613 us 
                                                      46 ns         3 ns        94 ns 
                                                                                      
(200x6) - Naive code                                    100            1     8.771 ms 
                                                  87.791 us    87.688 us    88.119 us 
                                                     841 ns       277 ns      1.84 us 
                                                                                      
(200x6) - ViSP                                          100            1   13.4548 ms 
                                                 132.979 us   132.873 us   133.167 us 
                                                     699 ns       441 ns     1.024 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84    2.0244 ms 
                                                     241 ns       241 ns       243 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          126    2.0034 ms 
                                                     159 ns       159 ns       161 ns 
                                                       4 ns         1 ns         9 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0304 ms 
                                                     564 ns       563 ns       569 ns 
                                                       9 ns         0 ns        23 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           76     2.014 ms 
                                                     266 ns       265 ns       271 ns 
                                                       8 ns         0 ns        21 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4     2.094 ms 
                                                   5.243 us     5.228 us     5.264 us 
                                                      88 ns        64 ns       134 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1208 ms 
                                                   1.935 us      1.93 us     1.961 us 
                                                      51 ns         3 ns       123 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9214 ms 
                                                   14.76 us    14.679 us    14.854 us 
                                                     444 ns       387 ns       522 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1244 ms 
                                                   5.317 us     5.298 us     5.407 us 
                                                     180 ns         8 ns       429 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8758 ms 
                                                  28.809 us    28.772 us    28.933 us 
                                                     305 ns        77 ns       679 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0698 ms 
                                                  10.376 us    10.324 us    10.582 us 
                                                     439 ns        28 ns     1.016 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84     2.016 ms 
                                                     239 ns       239 ns       242 ns 
                                                       5 ns         0 ns        12 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          129    2.0124 ms 
                                                     156 ns       156 ns       157 ns 
                                                       3 ns         1 ns         6 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0268 ms 
                                                     561 ns       560 ns       565 ns 
                                                       8 ns         0 ns        19 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           77    2.0097 ms 
                                                     262 ns       261 ns       266 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0888 ms 
                                                   5.226 us     5.212 us     5.246 us 
                                                      81 ns        61 ns       126 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1175 ms 
                                                   1.935 us     1.929 us     1.955 us 
                                                      50 ns         3 ns       110 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9014 ms 
                                                   14.55 us    14.495 us    14.629 us 
                                                     332 ns       250 ns       427 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1204 ms 
                                                   5.342 us     5.328 us      5.41 us 
                                                     137 ns         5 ns       326 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8751 ms 
                                                  28.798 us    28.753 us    28.909 us 
                                                     331 ns        92 ns       594 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0626 ms 
                                                  10.426 us    10.397 us    10.563 us 
                                                     277 ns        12 ns       661 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- Results:
  - improvement for `matrix-homogeneous matrix multiplication`
  - perf degradation for `AAt`
  - improvement for `matrix-velocity twist multiplication`
  - improvement for `matrix-force twist multiplication`
  - Netlib gives ~2x speed improvement for DGEMM wrt naive code
  - Netlib is ~1.5x slower for DGEMV wrt naive code

### ./testGenericTracker -d -D

- Before:

```
Computation time, Mean: 43.0357 ms ; Median: 39.5701 ms ; Std: 16.4938 ms
Max translation error: 0.00111751
Max thetau error: 0.373702
Features, Mean: 51402.6 ; Median: 46066.5 ; Std: 13881.3
```

- After:

```
Computation time, Mean: 39.7924 ms ; Median: 36.0449 ms ; Std: 15.3238 ms
Max translation error: 0.00111751
Max thetau error: 0.373702
Features, Mean: 51402.6 ; Median: 46066.5 ; Std: 13881.3
```

**Comment by s-trinh** [comment]
## Test with Docker Ubuntu 18.04 - Atlas

<details><summary>ViSP-third-party.txt (master branch @ 09ff01c)</summary>
<p>

```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-06T00:16:58Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Use MKL:                     no
    Use OpenBLAS:                no
    Use Atlas:                   no
    Use Netlib Lapack:           no
    Use Lapack (built-in):       yes (ver 3.2.1)
    Use Eigen3:                  no
    Use OpenCV:                  no
    Use GSL:                     no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

<details><summary>ViSP-third-party.txt (PR branch)</summary>
<p>


```
==========================================================
General configuration information for ViSP 3.3.1

  Version control:               unknown

  Platform:
    Timestamp:                   2020-04-05T20:54:36Z
    Host:                        Linux 4.15.0-91-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      yes
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C++ flags (Debug):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -O3 -DNDEBUG
    C flags (Debug):             -Wall -Wextra -fopenmp -std=c++11 -fvisibility=hidden -mavx -fPIC -g
    Linker flags (Release):
    Linker flags (Debug):

  ViSP modules:
    To be built:                 core gui imgproc io java_bindings_generator klt me sensor ar blob robot visual_features vs vision detection mbt tt tt_mi
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 java

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO

  Build options: 
    Build deprecated:            yes
    Build with moment combine:   no

  Mathematics: 
    Blas/Lapack:                 yes
    \- Use MKL:                  no
    \- Use OpenBLAS:             no
    \- Use Atlas:                no
    \- Use Netlib:               no
    \- Use GSL:                  no
    \- Use Lapack (built-in):    yes (ver 3.2.1)
    Use Eigen3:                  no
    Use OpenCV:                  no

  Simulator: 
    Ogre simulator: 
    \- Use Ogre3D:               no
    \- Use OIS:                  no
    Coin simulator: 
    \- Use Coin3D:               no
    \- Use SoWin:                no
    \- Use SoXt:                 no
    \- Use SoQt:                 no
    \- Use Qt5:                  no
    \- Use Qt4:                  no
    \- Use Qt3:                  no

  Media I/O: 
    Use JPEG:                    no
    Use PNG:                     no
    \- Use ZLIB:                 no
    Use OpenCV:                  no
    Use stb_image (built-in):    yes (ver 2.22.0)

  Real robots: 
    Use Afma4:                   no
    Use Afma6:                   no
    Use Franka:                  no
    Use Viper650:                no
    Use Viper850:                no
    Use aria (Pioneer):          no
    Use PTU46:                   no
    Use Biclops PTU:             no
    Use Flir PTU SDK:            no
    Use Parrot ARSDK:            no
    \-Use ffmpeg:                no
    Use Virtuose:                no
    Use qbdevice (built-in):     yes (ver 2.6.0)

  GUI: 
    Use X11:                     yes
    Use GTK:                     no
    Use OpenCV:                  no
    Use GDI:                     no
    Use Direct3D:                no

  Cameras: 
    Use DC1394-2.x:              no
    Use CMU 1394:                no
    Use V4L2:                    no
    Use directshow:              no
    Use OpenCV:                  no
    Use Flycapture:              no
    Use Pylon:                   no

  RGB-D sensors: 
    Use Realsense:               no
    Use Realsense2:              no
    Use Kinect:                  no
    \- Use libfreenect:          no
    \- Use libusb-1:             no
    \- Use pthread:              yes
    Use PCL:                     no
    \- Use VTK:                  no

  F/T sensors: 
    Use atidaq (built-in):       no
    Use comedi:                  no
    Use IIT SDK:                 no

  Detection: 
    Use zbar:                    no
    Use dmtx:                    no
    Use AprilTag (built-in):     yes (ver 3.1.1)
    \- Use AprilTag big family:  no

  Misc: 
    Use Clipper (built-in):      no
    Use pugixml (built-in):      yes (ver 1.9.0)
    Use libxml2:                 no

  Optimization: 
    Use OpenMP:                  yes
    Use pthread:                 yes
    Use pthread (built-in):      no
    Use cxx standard:            11

  Documentation: 
    Use doxygen:                 no

  Tests and samples:
    Use catch2 (built-in):       yes (ver 2.9.2)
    Tests:                       yes
    Demos:                       no
    Examples:                    no
    Tutorials:                   no

  Install path:                  /usr/local

==========================================================
```

</p>
</details>

### ./perfMatrixMultiplication --benchmark

- Before:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          239    2.0076 ms 
                                                      84 ns        83 ns        92 ns 
                                                      15 ns         0 ns        37 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          236     2.006 ms 
                                                      86 ns        84 ns        92 ns 
                                                      13 ns         0 ns        32 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           96     2.016 ms 
                                                     209 ns       209 ns       210 ns 
                                                       3 ns         0 ns         5 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           93    2.0181 ms 
                                                     214 ns       214 ns       215 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           53    2.0299 ms 
                                                     379 ns       378 ns       382 ns 
                                                       9 ns         4 ns        19 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           52    2.0228 ms 
                                                     392 ns       383 ns       432 ns 
                                                      80 ns         0 ns       191 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31    2.0212 ms 
                                                     646 ns       646 ns       649 ns 
                                                       7 ns         0 ns        16 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           31    2.0646 ms 
                                                     660 ns       659 ns       664 ns 
                                                       9 ns         1 ns        18 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.1212 ms 
                                                    5.31 us     5.306 us     5.325 us 
                                                      35 ns         4 ns        83 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            4    2.0804 ms 
                                                   5.202 us     5.193 us     5.245 us 
                                                      87 ns         5 ns       207 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.0934 ms 
                                                   6.971 us     6.963 us     6.994 us 
                                                      58 ns         5 ns       125 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            3    2.1015 ms 
                                                   6.979 us     6.972 us     7.009 us 
                                                      70 ns         6 ns       167 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1   15.2505 ms 
                                                   152.7 us   152.513 us   153.155 us 
                                                    1.39 us       586 ns     2.571 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1   15.2595 ms 
                                                 152.567 us   152.479 us   152.705 us 
                                                     550 ns       361 ns       784 ns 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   469.402 ms 
                                                  4.6967 ms   4.69423 ms   4.70219 ms 
                                                  17.868 us     7.731 us    30.666 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   467.207 ms 
                                                 4.67577 ms   4.67328 ms   4.68129 ms 
                                                  17.955 us     9.882 us    33.311 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   131.758 ms 
                                                 1.31523 ms   1.31483 ms   1.31626 ms 
                                                   3.038 us     1.494 us     6.268 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   131.452 ms 
                                                 1.31181 ms   1.31143 ms   1.31255 ms 
                                                   2.597 us     1.566 us     4.604 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1     14.831 s 
                                                 146.075 ms   146.049 ms   146.115 ms 
                                                 163.574 us   119.423 us   233.346 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1    14.5655 s 
                                                 144.389 ms   144.363 ms   144.424 ms 
                                                 154.018 us   125.005 us    204.56 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.94812 s 
                                                   99.54 ms   99.5201 ms   99.5669 ms 
                                                 117.076 us    93.395 us   165.518 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    9.89825 s 
                                                 98.8311 ms   98.8181 ms   98.8488 ms 
                                                  76.864 us    62.752 us   107.028 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          181    2.0091 ms 
                                                     111 ns       111 ns       112 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          252     2.016 ms 
                                                      80 ns        80 ns        81 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          146    2.0148 ms 
                                                     139 ns       139 ns       140 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          145      2.03 ms 
                                                     140 ns       140 ns       141 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          295     2.006 ms 
                                                      69 ns        68 ns        69 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          289    1.9941 ms 
                                                      69 ns        69 ns        69 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          244    2.0008 ms 
                                                      83 ns        82 ns        83 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          228    2.0064 ms 
                                                      89 ns        89 ns        90 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          202    1.9998 ms 
                                                     100 ns       100 ns       101 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          193    2.0265 ms 
                                                     105 ns       105 ns       106 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          165    2.0295 ms 
                                                     122 ns       122 ns       123 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          157    2.0096 ms 
                                                     128 ns       128 ns       129 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           69    2.0355 ms 
                                                     295 ns       295 ns       297 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           68      2.04 ms 
                                                     300 ns       299 ns       302 ns 
                                                       5 ns         1 ns        11 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           27    2.0196 ms 
                                                     746 ns       746 ns       748 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           27    2.0358 ms 
                                                     755 ns       754 ns       759 ns 
                                                       9 ns         0 ns        22 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18    2.0232 ms 
                                                   1.119 us     1.116 us     1.127 us 
                                                      19 ns         4 ns        42 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           20     2.092 ms 
                                                   1.048 us     1.045 us     1.059 us 
                                                      25 ns         2 ns        58 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2     3.063 ms 
                                                  16.287 us     15.73 us    17.312 us 
                                                   3.738 us     2.264 us     5.772 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            2    3.0288 ms 
                                                  15.142 us     15.12 us    15.227 us 
                                                     194 ns        38 ns       457 ns 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.2384 ms 
                                                  11.247 us    11.205 us    11.403 us 
                                                     359 ns        51 ns       823 ns 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            2    2.2334 ms 
                                                  11.233 us    11.181 us    11.443 us 
                                                     456 ns        39 ns     1.059 us 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   20.4462 ms 
                                                 205.681 us   204.393 us   210.129 us 
                                                  10.245 us       720 ns    23.087 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1   20.5275 ms 
                                                 206.991 us   205.422 us   211.327 us 
                                                  12.233 us     4.855 us    25.603 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1    15.745 ms 
                                                 158.601 us   157.414 us   161.864 us 
                                                   8.707 us       989 ns    17.739 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   15.7328 ms 
                                                 158.949 us   157.446 us   162.891 us 
                                                  10.895 us       909 ns    22.129 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          264    2.0064 ms 
                                                      76 ns        76 ns        77 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100          261    2.0097 ms 
                                                      78 ns        77 ns        78 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6) - Naive code                                      100          130     2.028 ms 
                                                     159 ns       156 ns       166 ns 
                                                      24 ns        14 ns        38 ns 
                                                                                      
(6x6) - ViSP                                            100          131    2.0305 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0216 ms 
                                                     266 ns       265 ns       267 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           76    2.0292 ms 
                                                     268 ns       267 ns       270 ns 
                                                       4 ns         1 ns        10 ns 
                                                                                      
(10x10) - Naive code                                    100           46    2.0516 ms 
                                                     448 ns       447 ns       450 ns 
                                                       4 ns         1 ns        11 ns 
                                                                                      
(10x10) - ViSP                                          100           45     2.034 ms 
                                                     453 ns       452 ns       455 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0825 ms 
                                                    2.99 us     2.976 us     3.042 us 
                                                     113 ns         3 ns       261 ns 
                                                                                      
(20x20) - ViSP                                          100            7    2.0678 ms 
                                                   2.955 us     2.952 us     2.967 us 
                                                      27 ns         2 ns        65 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3184 ms 
                                                  93.258 us    93.138 us    93.692 us 
                                                   1.011 us       264 ns     2.295 us 
                                                                                      
(6x200) - ViSP                                          100            1    9.3593 ms 
                                                  93.625 us    93.534 us    93.786 us 
                                                     605 ns       400 ns     1.065 us 
                                                                                      
(200x6) - Naive code                                    100            5     2.036 ms 
                                                   4.076 us     4.072 us     4.089 us 
                                                      33 ns         3 ns        71 ns 
                                                                                      
(200x6) - ViSP                                          100            5    2.0395 ms 
                                                   4.081 us     4.078 us     4.092 us 
                                                      23 ns         2 ns        56 ns 
                                                                                      
(207x119) - Naive code                                  100            1    141.96 ms 
                                                 1.41942 ms   1.41883 ms   1.42074 ms 
                                                   4.279 us     2.333 us     8.488 us 
                                                                                      
(207x119) - ViSP                                        100            1   141.872 ms 
                                                 1.41898 ms   1.41851 ms   1.42034 ms 
                                                   3.772 us     1.537 us     8.166 us 
                                                                                      
(83x201) - Naive code                                   100            1    147.75 ms 
                                                 1.47681 ms   1.47629 ms   1.47779 ms 
                                                   3.505 us     2.253 us     5.852 us 
                                                                                      
(83x201) - ViSP                                         100            1   147.427 ms 
                                                 1.47371 ms   1.47319 ms   1.47516 ms 
                                                   4.081 us     1.815 us     8.654 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.32069 s 
                                                 53.2188 ms    53.208 ms   53.2357 ms 
                                                  67.906 us     47.77 us   100.749 us 
                                                                                      
(600x400) - ViSP                                        100            1    5.32031 s 
                                                 53.2102 ms   53.1799 ms   53.2717 ms 
                                                 210.786 us   118.603 us   343.958 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.40892 s 
                                                 74.0874 ms   74.0774 ms   74.1028 ms 
                                                  62.076 us    45.515 us   101.914 us 
                                                                                      
(400x600) - ViSP                                        100            1    7.40803 s 
                                                 74.0247 ms   74.0095 ms   74.0528 ms 
                                                  101.59 us    65.235 us   177.305 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          255    2.0145 ms 
                                                      78 ns        78 ns        79 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(3x3) - ViSP                                            100          258    2.0124 ms 
                                                      79 ns        78 ns        79 ns 
                                                       1 ns         1 ns         3 ns 
                                                                                      
(6x6) - Naive code                                      100          130     2.015 ms 
                                                     154 ns       154 ns       155 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100          130     2.015 ms 
                                                     155 ns       155 ns       156 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(8x8) - Naive code                                      100           76    2.0368 ms 
                                                     267 ns       267 ns       268 ns 
                                                       2 ns         1 ns         5 ns 
                                                                                      
(8x8) - ViSP                                            100           77    2.0405 ms 
                                                     268 ns       267 ns       269 ns 
                                                       3 ns         1 ns         6 ns 
                                                                                      
(10x10) - Naive code                                    100           48    2.0496 ms 
                                                     432 ns       431 ns       434 ns 
                                                       6 ns         0 ns        12 ns 
                                                                                      
(10x10) - ViSP                                          100           48      2.04 ms 
                                                     427 ns       426 ns       429 ns 
                                                       5 ns         1 ns        10 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.1696 ms 
                                                   2.721 us     2.715 us     2.734 us 
                                                      38 ns         3 ns        71 ns 
                                                                                      
(20x20) - ViSP                                          100            8     2.156 ms 
                                                   2.698 us     2.693 us     2.708 us 
                                                      28 ns         1 ns        53 ns 
                                                                                      
(6x200) - Naive code                                    100            6    2.3934 ms 
                                                   3.993 us     3.988 us     4.005 us 
                                                      34 ns         5 ns        63 ns 
                                                                                      
(6x200) - ViSP                                          100            6    2.4066 ms 
                                                   4.011 us     4.008 us     4.022 us 
                                                      25 ns         5 ns        60 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.6985 ms 
                                                  86.927 us    86.882 us    87.043 us 
                                                     334 ns        75 ns       600 ns 
                                                                                      
(200x6) - ViSP                                          100            1    8.6993 ms 
                                                  87.032 us    86.957 us    87.169 us 
                                                     501 ns       315 ns       772 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           85    2.0145 ms 
                                                     237 ns       237 ns       239 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          130     2.015 ms 
                                                     155 ns       154 ns       156 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0304 ms 
                                                     565 ns       564 ns       568 ns 
                                                       8 ns         1 ns        17 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           79    2.0382 ms 
                                                     264 ns       259 ns       276 ns 
                                                      34 ns        11 ns        71 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0428 ms 
                                                   5.118 us     5.113 us      5.14 us 
                                                      51 ns         6 ns       122 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1054 ms 
                                                   1.934 us     1.917 us     1.988 us 
                                                     132 ns         2 ns       288 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2     2.884 ms 
                                                   14.44 us    14.418 us    14.498 us 
                                                     159 ns        10 ns       309 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1252 ms 
                                                   5.329 us     5.317 us     5.385 us 
                                                     112 ns         6 ns       268 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8739 ms 
                                                  28.775 us    28.735 us    28.935 us 
                                                     388 ns        15 ns       925 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2     2.069 ms 
                                                  10.438 us    10.348 us    10.829 us 
                                                     790 ns        16 ns     1.866 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/ViSP-src/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           85     2.023 ms 
                                                     238 ns       237 ns       239 ns 
                                                       4 ns         0 ns         8 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           97    2.0273 ms 
                                                     210 ns       209 ns       211 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36     2.034 ms 
                                                     564 ns       563 ns       568 ns 
                                                       7 ns         0 ns        17 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           39    2.0358 ms 
                                                     523 ns       522 ns       525 ns 
                                                       5 ns         0 ns        10 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0496 ms 
                                                    5.11 us     5.104 us     5.133 us 
                                                      53 ns         6 ns       127 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100            5    2.4965 ms 
                                                   5.001 us     4.993 us     5.021 us 
                                                      57 ns         5 ns       113 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.9206 ms 
                                                  14.435 us    14.414 us    14.488 us 
                                                     149 ns         8 ns       270 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            2    2.8624 ms 
                                                  14.315 us      14.3 us    14.353 us 
                                                     106 ns         9 ns       207 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8711 ms 
                                                  28.755 us    28.706 us    28.875 us 
                                                     344 ns        22 ns       645 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            1    2.8294 ms 
                                                  28.351 us    28.297 us    28.483 us 
                                                     425 ns       211 ns       699 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- After:

<details><summary>log</summary>
<p>

```
./perfMatrixMultiplication --benchmark
Default matrix/vector min size to enable Blas/Lapack optimization: 0
Used matrix/vector min size to enable Blas/Lapack optimization: 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfMatrixMultiplication is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark matrix-matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:217
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          239    1.9837 ms 
                                                      84 ns        84 ns        84 ns 
                                                       0 ns         0 ns         2 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          248     1.984 ms 
                                                      80 ns        80 ns        81 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x6) - Naive code                                100           95     2.014 ms 
                                                     214 ns       214 ns       216 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100           97    2.0079 ms 
                                                     207 ns       207 ns       208 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(8x8)x(8x8) - Naive code                                100           53    2.0087 ms 
                                                     377 ns       377 ns       380 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(8x8)x(8x8) - ViSP                                      100           54    2.0196 ms 
                                                     375 ns       374 ns       376 ns 
                                                       3 ns         0 ns         9 ns 
                                                                                      
(10x10)x(10x10) - Naive code                            100           31     2.015 ms 
                                                     651 ns       650 ns       656 ns 
                                                      10 ns         1 ns        23 ns 
                                                                                      
(10x10)x(10x10) - ViSP                                  100           31    1.9964 ms 
                                                     645 ns       644 ns       648 ns 
                                                       6 ns         0 ns        15 ns 
                                                                                      
(20x20)x(20x20) - Naive code                            100            4    2.1344 ms 
                                                   5.357 us     5.346 us     5.385 us 
                                                      83 ns        27 ns       147 ns 
                                                                                      
(20x20)x(20x20) - ViSP                                  100            4    2.0532 ms 
                                                   5.142 us     5.134 us     5.161 us 
                                                      54 ns         4 ns       100 ns 
                                                                                      
(6x200)x(200x6) - Naive code                            100            3    2.1066 ms 
                                                   7.023 us     7.018 us     7.046 us 
                                                      47 ns         5 ns       111 ns 
                                                                                      
(6x200)x(200x6) - ViSP                                  100            3     2.085 ms 
                                                   6.956 us     6.952 us     6.972 us 
                                                      37 ns         5 ns        89 ns 
                                                                                      
(200x6)x(6x200) - Naive code                            100            1    15.281 ms 
                                                 156.748 us   154.315 us   162.009 us 
                                                  17.398 us     8.573 us    29.333 us 
                                                                                      
(200x6)x(6x200) - ViSP                                  100            1   15.2409 ms 
                                                 152.396 us   152.318 us   152.532 us 
                                                     510 ns       334 ns       725 ns 
                                                                                      
(207x119)x(119x207) - Naive code                        100            1   475.159 ms 
                                                 4.73883 ms   4.73563 ms   4.74154 ms 
                                                  15.018 us     12.39 us    18.045 us 
                                                                                      
(207x119)x(119x207) - ViSP                              100            1   467.452 ms 
                                                 4.67371 ms    4.6732 ms   4.67456 ms 
                                                   3.283 us     2.193 us     4.953 us 
                                                                                      
(83x201)x(201x83) - Naive code                          100            1   133.298 ms 
                                                 1.33304 ms   1.33238 ms   1.33455 ms 
                                                   4.826 us     1.861 us     8.431 us 
                                                                                      
(83x201)x(201x83) - ViSP                                100            1   132.509 ms 
                                                 1.32433 ms    1.3232 ms    1.3274 ms 
                                                   8.756 us     3.891 us    18.418 us 
                                                                                      
(600x400)x(400x600) - Naive code                        100            1     14.797 s 
                                                 146.212 ms   146.194 ms   146.238 ms 
                                                 108.711 us    81.865 us   169.632 us 
                                                                                      
(600x400)x(400x600) - ViSP                              100            1    14.5317 s 
                                                 144.309 ms   144.256 ms   144.417 ms 
                                                 370.679 us   213.358 us   609.089 us 
                                                                                      
(400x600)x(600x400) - Naive code                        100            1    9.93824 s 
                                                 99.2588 ms   99.2463 ms   99.2755 ms 
                                                  73.306 us    57.846 us     96.49 us 
                                                                                      
(400x600)x(600x400) - ViSP                              100            1    9.85208 s 
                                                 98.5278 ms   98.5138 ms   98.5517 ms 
                                                  91.216 us    61.191 us   141.985 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-rotation matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:294
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x3) - Naive code                                100          181     1.991 ms 
                                                     111 ns       111 ns       112 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(3x3)x(3x3) - ViSP                                      100          242    1.9844 ms 
                                                      83 ns        83 ns        83 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-homogeneous matrix multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:379
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(4x4)x(4x4) - Naive code                                100          146    1.9856 ms 
                                                     136 ns       136 ns       137 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(4x4)x(4x4) - ViSP                                      100          186    1.9902 ms 
                                                     107 ns       107 ns       108 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-vector multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:467
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3)x(3x1) - Naive code                                100          293    1.9924 ms 
                                                      68 ns        68 ns        68 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(3x3)x(3x1) - ViSP                                      100          282    2.0022 ms 
                                                      71 ns        71 ns        72 ns 
                                                       0 ns         0 ns         1 ns 
                                                                                      
(6x6)x(6x1) - Naive code                                100          235    1.9975 ms 
                                                      86 ns        86 ns        87 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6)x(6x1) - ViSP                                      100          216    1.9872 ms 
                                                      92 ns        92 ns        93 ns 
                                                       2 ns         0 ns         4 ns 
                                                                                      
(8x8)x(8x1) - Naive code                                100          194    1.9982 ms 
                                                     102 ns       102 ns       103 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(8x8)x(8x1) - ViSP                                      100          191    1.9864 ms 
                                                     105 ns       104 ns       105 ns 
                                                       1 ns         0 ns         4 ns 
                                                                                      
(10x10)x(10x1) - Naive code                             100          160         2 ms 
                                                     125 ns       125 ns       126 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(10x10)x(10x1) - ViSP                                   100          152    1.9912 ms 
                                                     132 ns       132 ns       134 ns 
                                                       2 ns         0 ns         6 ns 
                                                                                      
(20x20)x(20x1) - Naive code                             100           65     2.002 ms 
                                                     308 ns       308 ns       310 ns 
                                                       4 ns         0 ns         7 ns 
                                                                                      
(20x20)x(20x1) - ViSP                                   100           67    1.9966 ms 
                                                     297 ns       296 ns       299 ns 
                                                       5 ns         0 ns        11 ns 
                                                                                      
(6x200)x(200x1) - Naive code                            100           26    2.0046 ms 
                                                     771 ns       770 ns       775 ns 
                                                       9 ns         0 ns        21 ns 
                                                                                      
(6x200)x(200x1) - ViSP                                  100           27    2.0304 ms 
                                                     754 ns       753 ns       757 ns 
                                                       8 ns         0 ns        19 ns 
                                                                                      
(200x6)x(6x1) - Naive code                              100           18     2.007 ms 
                                                   1.112 us      1.11 us     1.121 us 
                                                      22 ns         0 ns        52 ns 
                                                                                      
(200x6)x(6x1) - ViSP                                    100           19    1.9988 ms 
                                                   1.056 us     1.053 us     1.065 us 
                                                      23 ns         1 ns        50 ns 
                                                                                      
(207x119)x(119x1) - Naive code                          100            2    2.9234 ms 
                                                  14.657 us    14.594 us    14.918 us 
                                                     561 ns        55 ns     1.309 us 
                                                                                      
(207x119)x(119x1) - ViSP                                100            2    2.8982 ms 
                                                  14.562 us    14.482 us    14.877 us 
                                                     684 ns        60 ns     1.586 us 
                                                                                      
(83x201)x(201x1) - Naive code                           100            2    2.1288 ms 
                                                  10.718 us    10.652 us    10.988 us 
                                                     576 ns        24 ns     1.349 us 
                                                                                      
(83x201)x(201x1) - ViSP                                 100            2    2.1572 ms 
                                                  10.905 us    10.828 us     11.25 us 
                                                     709 ns        47 ns     1.676 us 
                                                                                      
(600x400)x(400x1) - Naive code                          100            1   21.2392 ms 
                                                 213.745 us   212.367 us    217.75 us 
                                                  10.249 us       696 ns    21.652 us 
                                                                                      
(600x400)x(400x1) - ViSP                                100            1   20.9909 ms 
                                                 211.384 us   210.038 us   215.689 us 
                                                  10.843 us     1.954 us    23.421 us 
                                                                                      
(400x600)x(600x1) - Naive code                          100            1   16.6078 ms 
                                                 167.321 us   166.069 us   170.645 us 
                                                   9.466 us     2.506 us    18.487 us 
                                                                                      
(400x600)x(600x1) - ViSP                                100            1   16.4867 ms 
                                                 166.409 us   164.961 us   169.939 us 
                                                  10.724 us     3.127 us    19.396 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AtA
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:548
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          261    1.9836 ms 
                                                      76 ns        76 ns        77 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100          264      1.98 ms 
                                                      76 ns        75 ns        76 ns 
                                                       1 ns         0 ns         2 ns 
                                                                                      
(6x6) - Naive code                                      100          126    1.9908 ms 
                                                     157 ns       156 ns       158 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100          127    1.9939 ms 
                                                     160 ns       160 ns       161 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(8x8) - Naive code                                      100           75    2.0025 ms 
                                                     267 ns       267 ns       269 ns 
                                                       4 ns         2 ns         8 ns 
                                                                                      
(8x8) - ViSP                                            100           76     2.014 ms 
                                                     267 ns       267 ns       268 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(10x10) - Naive code                                    100           44    1.9976 ms 
                                                     453 ns       452 ns       455 ns 
                                                       5 ns         0 ns        13 ns 
                                                                                      
(10x10) - ViSP                                          100           45     2.007 ms 
                                                     447 ns       447 ns       449 ns 
                                                       3 ns         0 ns         8 ns 
                                                                                      
(20x20) - Naive code                                    100            7    2.0923 ms 
                                                    2.99 us     2.987 us     3.008 us 
                                                      35 ns         3 ns        84 ns 
                                                                                      
(20x20) - ViSP                                          100            7    2.0692 ms 
                                                   2.962 us     2.957 us     2.975 us 
                                                      35 ns         3 ns        66 ns 
                                                                                      
(6x200) - Naive code                                    100            1    9.3661 ms 
                                                   94.39 us    93.734 us    97.116 us 
                                                    5.76 us       548 ns    13.388 us 
                                                                                      
(6x200) - ViSP                                          100            1    9.3577 ms 
                                                  93.611 us    93.486 us    94.024 us 
                                                   1.026 us       318 ns     2.266 us 
                                                                                      
(200x6) - Naive code                                    100            5    2.0395 ms 
                                                   4.074 us     4.072 us     4.081 us 
                                                      16 ns         3 ns        37 ns 
                                                                                      
(200x6) - ViSP                                          100            5    2.0355 ms 
                                                   4.074 us     4.071 us     4.085 us 
                                                      27 ns         3 ns        64 ns 
                                                                                      
(207x119) - Naive code                                  100            1    141.15 ms 
                                                 1.41167 ms   1.41139 ms   1.41212 ms 
                                                   1.776 us     1.197 us     2.724 us 
                                                                                      
(207x119) - ViSP                                        100            1   141.332 ms 
                                                 1.41226 ms   1.41191 ms   1.41282 ms 
                                                   2.203 us     1.503 us     3.523 us 
                                                                                      
(83x201) - Naive code                                   100            1   146.027 ms 
                                                   1.463 ms   1.46065 ms   1.47205 ms 
                                                  20.786 us     4.274 us    48.358 us 
                                                                                      
(83x201) - ViSP                                         100            1   146.291 ms 
                                                 1.46176 ms   1.46132 ms   1.46277 ms 
                                                   3.233 us      1.69 us     6.489 us 
                                                                                      
(600x400) - Naive code                                  100            1    5.48008 s 
                                                 54.8293 ms    54.818 ms   54.8494 ms 
                                                  74.858 us    49.255 us   128.039 us 
                                                                                      
(600x400) - ViSP                                        100            1    5.48177 s 
                                                 54.7893 ms   54.7801 ms     54.81 ms 
                                                  66.343 us     36.89 us   132.832 us 
                                                                                      
(400x600) - Naive code                                  100            1    7.43319 s 
                                                 74.3579 ms   74.3425 ms   74.3825 ms 
                                                  97.348 us    68.129 us   141.915 us 
                                                                                      
(400x600) - ViSP                                        100            1    7.43474 s 
                                                 74.3562 ms   74.3407 ms   74.3816 ms 
                                                  99.543 us    65.811 us   153.054 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark AAt
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:619
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(3x3) - Naive code                                      100          256    1.9968 ms 
                                                      78 ns        77 ns        78 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(3x3) - ViSP                                            100          261    1.9836 ms 
                                                      75 ns        75 ns        76 ns 
                                                       1 ns         0 ns         3 ns 
                                                                                      
(6x6) - Naive code                                      100          128    1.9968 ms 
                                                     160 ns       160 ns       161 ns 
                                                       2 ns         0 ns         5 ns 
                                                                                      
(6x6) - ViSP                                            100          128    2.0096 ms 
                                                     157 ns       157 ns       158 ns 
                                                       2 ns         1 ns         4 ns 
                                                                                      
(8x8) - Naive code                                      100           74     1.998 ms 
                                                     269 ns       269 ns       270 ns 
                                                       4 ns         2 ns         7 ns 
                                                                                      
(8x8) - ViSP                                            100           75      2.01 ms 
                                                     267 ns       266 ns       268 ns 
                                                       4 ns         1 ns         8 ns 
                                                                                      
(10x10) - Naive code                                    100           46     2.024 ms 
                                                     441 ns       441 ns       443 ns 
                                                       4 ns         0 ns        10 ns 
                                                                                      
(10x10) - ViSP                                          100           47     2.021 ms 
                                                     428 ns       428 ns       431 ns 
                                                       6 ns         0 ns        14 ns 
                                                                                      
(20x20) - Naive code                                    100            8    2.1936 ms 
                                                   2.746 us     2.741 us     2.759 us 
                                                      38 ns         3 ns        70 ns 
                                                                                      
(20x20) - ViSP                                          100            8    2.1656 ms 
                                                   2.704 us     2.699 us     2.715 us 
                                                      31 ns         4 ns        58 ns 
                                                                                      
(6x200) - Naive code                                    100            5    2.0155 ms 
                                                   4.027 us     4.025 us     4.032 us 
                                                      14 ns         5 ns        31 ns 
                                                                                      
(6x200) - ViSP                                          100            6    2.3916 ms 
                                                   3.991 us     3.985 us     4.005 us 
                                                      38 ns         2 ns        70 ns 
                                                                                      
(200x6) - Naive code                                    100            1    8.7324 ms 
                                                  87.332 us    87.283 us    87.454 us 
                                                     366 ns       112 ns       649 ns 
                                                                                      
(200x6) - ViSP                                          100            1    8.7319 ms 
                                                  87.308 us     87.22 us    87.542 us 
                                                     675 ns       301 ns     1.354 us 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-velocity twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:690
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84     2.016 ms 
                                                     238 ns       238 ns       240 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          130     2.002 ms 
                                                     154 ns       154 ns       156 ns 
                                                       4 ns         0 ns         9 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36    2.0268 ms 
                                                     562 ns       561 ns       565 ns 
                                                       8 ns         0 ns        16 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           77    2.0174 ms 
                                                     264 ns       263 ns       268 ns 
                                                       8 ns         0 ns        18 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0928 ms 
                                                   5.259 us     5.243 us      5.28 us 
                                                      93 ns        75 ns       122 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1417 ms 
                                                   1.937 us      1.93 us      1.96 us 
                                                      53 ns         7 ns       122 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2    2.8964 ms 
                                                  14.604 us    14.543 us     14.69 us 
                                                     366 ns       282 ns       473 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1472 ms 
                                                   5.415 us     5.394 us     5.499 us 
                                                     174 ns         9 ns       407 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8762 ms 
                                                  28.792 us    28.751 us    28.968 us 
                                                     378 ns        53 ns       893 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0624 ms 
                                                  10.393 us    10.359 us    10.528 us 
                                                     328 ns        14 ns       782 ns 
                                                                                      

-------------------------------------------------------------------------------
Benchmark matrix-force twist multiplication
-------------------------------------------------------------------------------
/workspace/visp/modules/core/test/math/perfMatrixMultiplication.cpp:775
...............................................................................

benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
(6x6)x(6x6) - Naive code                                100           84    2.0076 ms 
                                                     238 ns       237 ns       240 ns 
                                                       4 ns         0 ns        11 ns 
                                                                                      
(6x6)x(6x6) - ViSP                                      100          129    1.9995 ms 
                                                     155 ns       154 ns       156 ns 
                                                       3 ns         0 ns         7 ns 
                                                                                      
(20x6)x(6x6) - Naive code                               100           36     2.034 ms 
                                                     563 ns       561 ns       566 ns 
                                                       9 ns         0 ns        19 ns 
                                                                                      
(20x6)x(6x6) - ViSP                                     100           77    2.0097 ms 
                                                     262 ns       261 ns       265 ns 
                                                       7 ns         0 ns        18 ns 
                                                                                      
(207x6)x(6x6) - Naive code                              100            4    2.0932 ms 
                                                   5.245 us     5.229 us     5.272 us 
                                                     102 ns        71 ns       167 ns 
                                                                                      
(207x6)x(6x6) - ViSP                                    100           11    2.1219 ms 
                                                   2.063 us     1.993 us      2.19 us 
                                                     467 ns       297 ns       706 ns 
                                                                                      
(600x6)x(6x6) - Naive code                              100            2      2.91 ms 
                                                  14.581 us    14.524 us    14.663 us 
                                                     347 ns       269 ns       456 ns 
                                                                                      
(600x6)x(6x6) - ViSP                                    100            4    2.1524 ms 
                                                   5.409 us     5.392 us     5.469 us 
                                                     140 ns        20 ns       313 ns 
                                                                                      
(1201x6)x(6x6) - Naive code                             100            1    2.8745 ms 
                                                  28.799 us     28.76 us    28.954 us 
                                                     356 ns        49 ns       836 ns 
                                                                                      
(1201x6)x(6x6) - ViSP                                   100            2    2.0704 ms 
                                                   10.37 us    10.325 us    10.551 us 
                                                     395 ns        37 ns       917 ns 
                                                                                      

===============================================================================
All tests passed (60 assertions in 8 test cases)
```

</p>
</details>

- Results:
  - improvement for `matrix-homogeneous matrix multiplication`
  - ~improvement for `AAt`~
  - ~improvement for `matrix-velocity twist multiplication`~
  - improvement for `matrix-force twist multiplication`

### ./testGenericTracker -d -D

- Before:

```
Computation time, Mean: 43.6966 ms ; Median: 40.4124 ms ; Std: 16.7387 ms
Max translation error: 0.00111751
Max thetau error: 0.373702
Features, Mean: 51402.6 ; Median: 46066.5 ; Std: 13881.3
```

- After:

```
Computation time, Mean: 44.7269 ms ; Median: 40.8779 ms ; Std: 17.1377 ms
Max translation error: 0.00111751
Max thetau error: 0.373702
Features, Mean: 51402.6 ; Median: 46066.5 ; Std: 13881.3
```

**Comment by s-trinh** [comment]
In my opinion, we should:
- restore `blas_dgemm` for `vpMatrix vpMatrix::operator*(const vpVelocityTwistMatrix &V) const` and Intel MKL
- put Netlib priority just before Lapack built-in since it is just a reference implementation like the Lapack built-in in ViSP

---

Not sure if `update-alternatives --config libblas.so.3` works as intended. First tests below.

On a Docker with both Atlas and OpenBLAS packages installed, regardless of the choice of `Blas/Lapack`, OpenBLAS is linked (`update-alternatives --config libblas.so.3-<multiarch>` is configured by default, so OpenBLAS has the highest priority):

- with `\- Use Atlas:                yes`:

```
ldd perfMatrixMultiplication 
	linux-vdso.so.1 (0x00007fffa7143000)
	libvisp_core.so.3.3 => /workspace/build_Atlas-OpenBLAS_2/lib/libvisp_core.so.3.3 (0x00007f42769ae000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f427678f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f42763f1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4276068000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4275e50000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4275a5f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f427708e000)
	liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f42751d9000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f4274faa000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f4272d04000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f4272925000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4272721000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f42724e1000)
```

- with `\- Use OpenBLAS:             yes`:

```
ldd perfMatrixMultiplication 
	linux-vdso.so.1 (0x00007ffd09fe7000)
	libvisp_core.so.3.3 => /workspace/build_Atlas-OpenBLAS/lib/libvisp_core.so.3.3 (0x00007f0d2297d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0d2275e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0d223c0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0d22037000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d21e1f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0d21a2e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0d2305d000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f0d1f788000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f0d1f559000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f0d1f17a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0d1ef76000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f0d1ed36000)
```

To be checked again, but my first tests show that changing `update-alternatives --config libblas.so.3-<multiarch>` will not work and OpenBLAS will be used.

On a Docker with only `Atlas`:

```
ldd perfMatrixMultiplication 
	linux-vdso.so.1 (0x00007fff2efd2000)
	libvisp_core.so.3.3 => /workspace/build_Atlas/lib/libvisp_core.so.3.3 (0x00007f531f968000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f531f749000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f531f3ab000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f531f022000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f531ee0a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f531ea19000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5320048000)
	liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f531e15a000)
	libcblas.so.3 => /usr/lib/x86_64-linux-gnu/libcblas.so.3 (0x00007f531df38000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f531dd09000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f531d747000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f531d368000)
	libatlas.so.3 => /usr/lib/x86_64-linux-gnu/libatlas.so.3 (0x00007f531cddf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f531cbdb000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f531c99b000)
```

If `update-alternatives --config libblas.so.3-<multiarch>` and `update-alternatives --config liblapack.so.3-<multiarch>` are modified to use Atlas and before building ViSP, then after building ViSP we have:

```
ldd perfMatrixMultiplication 
	linux-vdso.so.1 (0x00007ffd30752000)
	libvisp_core.so.3.3 => /workspace/build_Atlas-OpenBLAS_2/lib/libvisp_core.so.3.3 (0x00007f170d7e2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f170d5c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f170d225000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f170ce9c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f170cc84000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f170c893000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f170dec2000)
	liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f170bfd4000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f170bda5000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f170b7e3000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f170b404000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f170b200000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f170afc0000)
```

Looks like ViSP is linked to `liblapack.so.3` and `libblas.so.3`, so now `update-alternatives --config libblas.so.3-<multiarch>` should work as intended I believe.

File: modules/detection/test/testAprilTag.cpp (hunk 7 above)
Comment (fspindle) [reply modules/detection/test/testAprilTag.cpp:733]: 1. I checked again that I'm able to reproduce the `testAprilTag` failure when Lapack is not used (`WITH_LAPACK=OFF` and all the `find_package()` were commented in `ChooseBLAS.cmake`). The smallest epsilon that makes the test successful is 1e-14. I will add an exception for this particular case:
    ```
    // Note that using epsilon = std::numeric_limits<double>::epsilon() makes this test
    // failing on Ubuntu 18.04 when none of the Lapack 3rd party libraries, nor the built-in are used.
    // Admissible espilon value is 1e-14. Using 1e-15 makes the test failing.
    #ifdef VISP_HAVE_LAPACK
        double epsilon = std::numeric_limits<double>::epsilon();
    #else
        double epsilon = 1e-12;
    #endif
    ```

2. When none of the 3rd parties (Lapack, OpenCv and Eigen3) are used, there is not only `testAprilTag` that fails. I will do the changes in an other PR after merging this one

File: CMakeLists.txt [hunk 10]
```diff
@@ -1422,14 +1418,15 @@ status("    Build with moment combine:"  ENABLE_MOMENTS_COMBINE_MATRICES THEN "y
...
-status("    Use MKL:"                USE_MKL            THEN "yes" ELSE "no")
-status("    Use OpenBLAS:"           USE_OPENBLAS       THEN "yes" ELSE "no")
-status("    Use Atlas:"              USE_ATLAS          THEN "yes" ELSE "no")
-status("    Use Netlib Lapack:"      USE_LAPACK_NETLIB  THEN "yes (ver ${LAPACK_C_VERSION})" ELSE "no")
-status("    Use Lapack (built-in):"  WITH_LAPACK        THEN "yes (ver ${LAPACK_VERSION})" ELSE "no")
+status("    Blas/Lapack:"            (USE_LAPACK OR WITH_LAPACK) THEN "yes" ELSE "no")
+status("    \\- Use MKL:"            USE_MKL            THEN "yes" ELSE "no")
+status("    \\- Use OpenBLAS:"       USE_OPENBLAS       THEN "yes" ELSE "no")
+status("    \\- Use Atlas:"          USE_ATLAS          THEN "yes" ELSE "no")
+status("    \\- Use Netlib:"         USE_LAPACK_NETLIB  THEN "yes (ver ${LAPACK_C_VERSION})" ELSE "no")
```
[the remark this answers is not in the document]
Comment (fspindle) [reply CMakeLists.txt:1425]: I can do it, but from the tests presented in `tutorial-basic-linear-algebra.doc` in Lapack performance comparison table, `Netlib` sounds faster than `GSL`.  That's why here the order of the 3rd parties is the performance order (1. `MKL`, 2. `OpenBlas`, 3. `Atlas`, 4. `Netlib`, 5. `GSL`, 6. `built_in`).

You don't agree with that choice ?

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc [hunk 11]
```diff
@@ -0,0 +1,295 @@
...
+  - vpMatrix::multMatrixVector(const vpMatrix &, const vpColVector &, vpColVector &)
+  - vpMatrix::mult2Matrices(const vpMatrix &, const vpColVector &, vpColVector &)
+  - vpMatrix::operator*(const vpColVector &) const
+- compute product \f${\bf A}^T {\bf A}\f$ or \f${\bf A} {\bf A}^T\f$ using either:
+  - vpMatrix::AtA()
+  - vpMatrix::AtA(vpMatrix &) const
+  - vpMatrix::AAt()
+  - vpMatrix::AAt(vpMatrix &) const
+
+These optimized operations are based on the use of BLAS and LAPACK third-party libraries. Several [optimized third-party](https://wiki.debian.org/DebianScience/LinearAlgebraLibraries) implementations are available for Lapack, but only one of the following third-party is used at the same time:
```
[the remark this answers is not in the document]
Comment (fspindle) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:24]: I agree

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc [hunk 12]
```diff
@@ -0,0 +1,295 @@
...
+      \verbatim
+$ echo "export MKLROOT=$HOME/intel/mkl" >> ~/.bashrc
+$ source ~/.bashrc
+      \endverbatim
+- [OpenBLAS](https://www.openblas.net/) an optimized BLAS library
+  - To install openBLAS on Ubuntu proceed with:
+    \verbatim
+$ sudo apt install libopenblas-dev
+    \endverbatim
+- [Netlib](https://www.netlib.org/) a collection of mathematical software
```
[the remark this answers is not in the document]
Comment (fspindle) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:49]: For the moment I will put `Netlib` before `GSL` to be coherent with the order in `CMakeLists.txt` (see my comment above)

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc [hunk 13]
```diff
@@ -0,0 +1,295 @@
...
+$ cd $VISP_WS/visp-build
+$ ccmake ../visp
+  \endverbatim
+  At this step, selection is achieved tuning the following line:
+  \verbatim
+USE_BLAS/LAPACK           [ MKL | OpenBLAS | Netlib | Atlas | GSL ]
+  \endverbatim
+- Note also that if you select `OpenBLAS`, or `Netlib` or `Atlas`, there is the possibility to change the used third-party during run time, without re-building ViSP. On Ubuntu, this could be achieved using `update-alternatives`:
+  \verbatim
+$ sudo update-alternatives --config liblapack.so.3-x86_64-linux-gnu
```
[the remark this answers is not in the document]
Comment (fspindle) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:82]: I need to check my benchmark results again using `update-alternatives` on `libblas` since I only change `liblapack` alternative!

-----
There is something strange in my Ubuntu 18.04:
```
$ update-alternatives --config liblapack.so.3
update-alternatives: error: no alternatives for liblapack.so.3
``` 
I need to run:
```
update-alternatives --config liblapack.so.3-x86_64-linux-gnu
There are 3 choices for the alternative liblapack.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/liblapack.so.3).

  Selection    Path                                               Priority   Status
------------------------------------------------------------
  0            /usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3   40        auto mode
  1            /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3      35        manual mode
  2            /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3     10        manual mode
* 3            /usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3   40        manual mode
```

Same for `libblas`
```
$ update-alternatives --config libblas.so.3
update-alternatives: error: no alternatives for libblas.so.3

$ update-alternatives --config libblas.so.3-x86_64-linux-gnu
There are 3 choices for the alternative libblas.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libblas.so.3).

  Selection    Path                                             Priority   Status
------------------------------------------------------------
* 0            /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3   40        auto mode
  1            /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3      35        manual mode
  2            /usr/lib/x86_64-linux-gnu/blas/libblas.so.3       10        manual mode
  3            /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3   40        manual mode
```

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc (hunk 8 above)
Comment (fspindle) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:271]: I don't know. For me `built-in` is just a conversion from Fortran to C. If I'm right it makes sense to have better results with `Netlib` than `built-in`

File: modules/core/src/math/matrix/vpMatrix.cpp (hunk 9 above)
Comment (fspindle) [reply modules/core/src/math/matrix/vpMatrix.cpp:1367]: I need to check on my side.

File: 3rdparty/clapack/blas/daxpy.c (hunk 1 above)
Comment (fspindle) [reply 3rdparty/clapack/blas/daxpy.c:1]: I used version 3.2.1 from [here](https://www.netlib.org/clapack/).
I didn't know that there exist 3.9.0 that I need definitively to consider.

File: modules/detection/test/testAprilTag.cpp (hunk 7 above)
Comment (s-trinh) [reply modules/detection/test/testAprilTag.cpp:745]: - I am ok as soon as we don't relax the threshold for the common cases (ViSP is built with MKL, OpenBLAS, or with built-in Lapack).
- So, when `WITH_LAPACK=OFF` and without `USE_BLAS`, it should be either `Eigen` or `OpenCV` that perform the calculation? I still don't see why we have this issue when Eigen or OpenCV is used, but for now it is fine since there is no regression.

File: CMakeLists.txt (hunk 10 above)
[the remark this answers is not in the document]
Comment (s-trinh) [reply CMakeLists.txt:1425]: I have some doubt with `update-alternatives --config libblas.so.3-<multiarch>`. I think somehow it does not work as intended. When Atlas and OpenBLAS are available, ViSP will be linked to `libopenblas.so.0`. So changing the alternative would not work.

[the remark this answers is not in the document]
Comment (s-trinh) [reply CMakeLists.txt:1425]: So, I think your results with Atlas and Netlib are wrong due to this issue.

Netlib is the reference Fortran Lapack code. There is no optimization and the benchmark results should be more or less equivalent between Netlib and Lapack built-in (minor the perf difference between the two languages and the compiler optimizations).

---

For instance, your results are:

| Operation | OpenBLAS | Atlas | Netlib | Built-in | Naive
| --- | --- | --- | --- | --- | --- |
| (600x400)x(400x600) | 3.19575 ms | 3.9736 ms | 3.61614 ms | 170.769 ms | 165.217 ms
| (400x600)x(600x400) | 2.01295 ms | 1.82563 ms | 1.79074 ms | 102.953 ms | 105.26 ms

Mine are:

| Operation | OpenBLAS | Atlas | Netlib | Built-in | Naive
| --- | --- | --- | --- | --- | --- |
| (600x400)x(400x600) | 1.43821 ms | 19.5031 ms | 60.6548 ms | 144.417 ms | 146.238 ms
| (400x600)x(600x400) | 985.012 us | 12.9778 ms | 40.6998 ms | 98.5517 ms | 99.2755 ms

I am using Docker with different images where only Atlas, OpenBLAS or Netlib are installed.

[the remark this answers is not in the document]
Comment (s-trinh) [reply CMakeLists.txt:1425]: I would put GSL at the same level than Eigen. [GSL](https://www.gnu.org/software/gsl/) does more than just providing the Lapack routines. And it can use a 3rd party BLAS library: [Using the GSL with an optimized BLAS](https://wiki.debian.org/DebianScience/LinearAlgebraLibraries).

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc (hunk 13 above)
[the remark this answers is not in the document]
Comment (s-trinh) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc:82]: See https://wiki.debian.org/DebianScience/LinearAlgebraLibraries
Since buster it is:
```
update-alternatives --config libblas.so.3-<multiarch>
update-alternatives --config liblapack.so.3-<multiarch>
```

File: CMakeLists.txt (hunk 10 above)
[the remark this answers is not in the document]
Comment (fspindle) [reply CMakeLists.txt:1425]: We cannot put GSL at the same level as Eigen because of the incompatibility between GSL and MKL (see issue #735) that was originally the reason of this PR. There should be a mutual exclusion between GSL and MKL. Even if GSL can do more than Lapack, my choice to consider GSL as a Lapack 3rdparty was motivated by the fact that in ViSP GSl is used to perform similar linear algebra operation than MKL, OpenBLAS, Atlas, Netlib

File: doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc [hunk 14]
```diff
@@ -0,0 +1,295 @@
...
+      \verbatim
+$ cd ~/Download
+$ tar xvzf l_mkl_2020.0.166.tgz
+      \endverbatim
+    - Run the installer and chose an installation location. By default installation location is set to `$HOME/intel`.
+      \verbatim
+$ cd l_mkl_2020.0.166
+$ ./install_GUI.sh
+      \endverbatim
+    - Set `MKLROOT` environment var to be able to detect MKL during cmake configuration. If you keep the default installation location as `$HOME/intel` simply run:
```
[the remark this answers is not in the document]
Comment (fspindle) [reply doc/tutorial/linear-algebra/tutorial-basic-linear-algebra.doc]: Done, thanks

File: modules/core/src/math/matrix/vpMatrix.cpp (hunk 9 above)
Comment (fspindle) [reply modules/core/src/math/matrix/vpMatrix.cpp:1367]: The table below shows the mean time obtained on my Ununtu laptop:

| testGenericTracker -d -D                                                                       | sample step<br>me=1<br>dense=4 | sample step<br>me=4<br>dense=4 | sample step<br>me=8<br>dense=4 | sample step<br>me=2<br>dense=1<br> |
|------------------------------------------------------------------------------------------------|:------------------------------:|:------------------------------:|:------------------------------:|:----------------------------------:|
| master branch                                                                                  | 16.4681 ms                     | 7.22376 ms                     | 5.60572 ms                     | 40.8489 ms                         |
| With PR #736 and MKL                                                                           | 17.3494 ms                     | 8.10851 ms                     | 5.65789 ms                     | 42.8151 ms                         |
| With PR #736 and MKL plus<br>`mult2Matrices(vpHomogeneousMatrix)`<br>using `MKL::blas_dgemm`                                 | 16.844 ms                      | 7.2696 ms                      | 5.60208 ms                     | 42.3033 ms                         |
| With PR #736 and MKL plus<br>`mult2Matrices(vpHomogeneousMatrix)`<br>`operator*(vpVelocityTwistMatrix)`<br>using `MKL::blas_dgemm` | 16.3295 ms                     | 6.99961 ms                     | 5.42807 ms                     | 39.8107 ms                         |

You are right, I will also introduce `blas_dgemm` in `vpMatrix::mult2Matrices(const vpMatrix &A, const vpMatrix &B, vpHomogeneousMatrix &C)` and `vpMatrix::operator*(const vpVelocityTwistMatrix &V)` since the table shows similar results or a small time improvement (between first and last table lines).

Without using `blas_dgemm` we can see a perf decrease (lines 2 and 3).

**Comment by fspindle** [comment]
I was able to reproduce your behavior with Docker ;-)
My understanding concerning the blas/lapack alternatives is the following:

- When `libatlas-base-dev` and `libopenblas-dev` are installed
- When `update-alternatives` is pointing to `openblas/liblapack.so.3` and `openblas/libblas.so.3` (this is the default case)
  - When `USE_BLAS/LAPACK=OpenBLAS` (default case)
    - `perfMatrixMultiplication` is linked to `libopenblas` which is expected:
        ```
        $ ldd perfMatrixMultiplication
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0
        ```
    - Now if  `update-alternatives` is used to point to `atlas/liblapack.so.3` and `atlas/libblas.so.3`, `perfMatrixMultiplication` doesn't swith to Atlas usage. We continue to use OpenBLAS:
        ```
        $ ldd perfMatrixMultiplication
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0
        ```
- When `update-alternatives` is now pointing to `atlas/liblapack.so.3` and `atlas/libblas.so.3`
  - When doing a fresh build with `USE_BLAS/LAPACK=OpenBLAS` (default case)
    - `perfMatrixMultiplication` is again linked to `libopenblas` which is not expected:
        ```
        $ ldd perfMatrixMultiplication
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0
        ```
- When `update-alternatives` continues to point to `atlas/liblapack.so.3` and `atlas/libblas.so.3`
  - When modifying `USE_BLAS/LAPACK=Atlas` (no need of a fresh build)
    - `perfMatrixMultiplication` is again linked to Atlas which is expected
        ```
        $ ldd perfMatrixMultiplication
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3
        $ ll /usr/lib/x86_64-linux-gnu/liblapack.so.3
        /usr/lib/x86_64-linux-gnu/liblapack.so.3 -> /etc/alternatives/liblapack.so.3-x86_64-linux-gnu
        $ ll /etc/alternatives/liblapack.so.3-x86_64-linux-gnu
        /etc/alternatives/liblapack.so.3-x86_64-linux-gnu -> /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3
        ```
        Similar investigations show that `/usr/lib/x86_64-linux-gnu/libblas.so.3` is pointing to `/usr/lib/x86_64-linux-gnu/atlas/libblas.so.3`
    - Now if  `update-alternatives` is used to point to `openblas/liblapack.so.3` and `openblas/libblas.so.3`, `perfMatrixMultiplication` is swithing to OpenBLAS usage as expected:
        ```
        $ ldd perfMatrixMultiplication
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0
        ```
        and `/usr/lib/x86_64-linux-gnu/liblapack.so.3` is pointing to `/usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3`


To resume:
- using  `USE_BLAS/LAPACK=OpenBLAS` doesn't allow to use  `update-alternatives` as expected
- while  `USE_BLAS/LAPACK=Atlas` makes  `update-alternatives` working

The only explaination I see for the moment is that in `FindOpenBLAS.cmake` we are searching explicitly `openblas` library:
```
FIND_LIBRARY(OpenBLAS_LIB NAMES openblas
```
while in `FindAtlas.cmake` we are searching an alternative `lapack` library:
```
find_library(Atlas_LAPACK_LIBRARY NAMES lapack
```
The fix could be to modify `FindOpenBLAS.cmake` to search `lapack` instead of `openblas` library as for Netlib where in `FindLAPACK_C.cmake` we are searching `lapack` and `blas` libraries.

**Comment by fspindle** [comment]
The last commits are fixing remaining issues.

- Now `update-alternatives` is working and allows to switch without rebuilding ViSP between OpenBLAS, Atlas and Netlib. The trick was to modify `FindOpenBLAS.cmake`
- `FindLAPACK_C.cmake` is now renamed in `FindNetlib.cmake` for clarity
- BLAS/LAPACK priority order is now MKL, OpenBLAS, Atlas, GSL, Netlib
- Performances using MKL remain similar than the one obtained prior this PR (tested with `testGenericTracker.cpp` and `photometricVisualServoingWithoutVpServo.cpp`. 

What remains to be done after merging this PR:
- Update Lapack built-in from 3.2.0 version to [3.9.0 version](https://github.com/Reference-LAPACK/lapack/releases)
- Fix `ctest` when LAPACK, Eigen3 and OpenCV are not used
